### ISSUE TITLE
Submit proof error. error="Method not found" and error="invalid degree: 0"

### ISSUE THREAD

**Issue by M2l2koPOWER** [taikoxyz/simple-taiko-node#120]
**simple-taiko-node-taiko_client_prover_relayer-1** throw an errors **"Method not found"** and **"invalid degree: 0"** after proof generation. What can be the problem and how does it affect L3 operation?

**Comment by davidtaikocha** [comment]
Should have been fixed now, feel free to reopen this if it still exists.
