### ISSUE TITLE
link of guide at https://github.com/taikoxyz/simple-taiko-node is wrong

### ISSUE THREAD

**Issue by LamborghiniMiura** [taikoxyz/simple-taiko-node#127]
Get started with the [guide](https://taiko.xyz/docs/guides/run-a-node).  is directing to wrong url which is https://taiko.xyz/docs/guides/run-a-node, correct url should be https://taiko.xyz/docs/guides/run-a-taiko-node
Get started with the [guide](https://taiko.xyz/docs/guides/run-a-taiko-node).

**Comment by davidtaikocha** [comment]
Should have been fixed now.
