### ISSUE TITLE
Incorrect Chain ID in .env file for Jolnir L2 in GitHub Repository

### ISSUE THREAD

**Issue by samui68400** [taikoxyz/simple-taiko-node#135]
Hello,

I was following the documentation provided on https://taiko.xyz/docs/guides/run-a-taiko-node to set up a Taiko node. According to the documentation, I copied the .env.sample file to a new file named .env using the command cp .env.sample .env. After initiating my node, I noticed that the block synchronization did not match the block numbers available on the explorer.

Seeking help, I visited the project's Discord channel. However, I decided to dig deeper into the issue by myself. Upon reviewing the contents of the .env file, I realized that the Chain ID specified for the Jolnir L2 was 1670005 (Grimsvotn) which seems to be incorrect. The correct Chain ID should be 167007 (Eldfell). This discrepancy was not mentioned anywhere in the documentation, which could lead to confusion and improper node setup.

I believe an amendment in either the documentation or the .env.sample file regarding the correct Chain ID for Jolnir L2 will be beneficial for future node setups.

Thank you for your attention to this matter. I look forward to any updates that may rectify this issue.

Best regards,

**Comment by spachib** [comment]
Was this a previous installation from the earlier testnets? Perhaps you didn't upgrade properly. I've found sometimes I have to completely remove the docker volumes on new testnet launch.  `sudo` docker compose down -v`

**Comment by davidtaikocha** [comment]
> Was this a previous installation from the earlier testnets? Perhaps you didn't upgrade properly. I've found sometimes I have to completely remove the docker volumes on new testnet launch. `sudo docker compose down -v`

Yes thats the reason, `sudo docker compose down -v` will address it.

**Comment by samui68400** [comment]
@spachib @davidtaikocha

Thank you for your feedback. Following your advice, I completely uninstalled my node and then reinstalled it. 
This approach successfully resolved the issue I was facing. 
I appreciate your guidance on this matter. It might be helpful for others if this troubleshooting step is included in the documentation, given that it can be a common pitfall for those transitioning from earlier testnets.

Thanks again for your support!
