### ISSUE TITLE
Server hardware configuration requirement

### ISSUE THREAD

**Issue by aligh98** [taikoxyz/simple-taiko-node#14]
What config is required for launching the Taiko node?
I saw that Optimism has this recommended:
```
Recommended Hardware
16GB+ RAM
500GB+ disk (HDD works for now, SSD is better)
10mb/s+ download
```

**Comment by dong77** [comment]
Thank you for this issue. We'll keep it open and wait until all ZKP integration is done. Then we'll have a better idea of what hardware is required to run a read-only node, a proposer, and/or a prover.

**Comment by aligh98** [comment]
I see the details added to README.md
https://github.com/taikoxyz/simple-taiko-node/blob/main/README.md#whats-the-system-requirements
