### ISSUE TITLE
Bash script with all the commands

### ISSUE THREAD

**Issue by tudorpintea999** [taikoxyz/simple-taiko-node#140]
A bash script containing all the commands from the tutorial to make it easier to install the node

**Comment by RandpappyB** [comment]
I cannot open .env with any of my text editors either in taiko or eth-doc

**Comment by mask-pp** [comment]
> A bash script containing all the commands from the tutorial to make it easier to install the node

It's handy for us to run on our local machine.

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/simple-taiko-node/pull/145
