### ISSUE TITLE
 sudo docker-compose up -d

### ISSUE THREAD

**Issue by viponedream** [taikoxyz/simple-taiko-node#143]
taiko_client_prover_relayer_1  | /bin/sh: /script/start-prover-relayer.sh: Permission denied

**Comment by MarcusWentz** [comment]
Q1. Do you see this issue if you delete then download `simple-taiko-node` again?

Q2. Do you have this permission issue with other docker containers?

**Comment by szefo8181** [comment]
I had a similar issue. It occurred when I created a new user account and assigned it administrator privileges. Later, when I tried to install Node.js, I encountered a problem with accessing various files related to permissions. The installation proceeded without issues when it was executed from an account with root privileges.

**Comment by davidtaikocha** [comment]
Closed due to inactive, feel free to open it again.
