### ISSUE TITLE
Permission denied on prover relayer

### ISSUE THREAD

**Issue by Cordeiro71** [taikoxyz/simple-taiko-node#159]
I have this error: taiko_client_prover_relayer_1 | /bin/sh: /script/start-prover-relayer.sh: Permission denied

**Comment by davidtaikocha** [comment]
Plz check: https://taiko.xyz/docs/reference/node-troubleshooting#simple-taiko-node-taiko_client_prover_relayer-1---binsh-scriptstart-prover-relayersh-not-found
