### ISSUE TITLE
Dial ethclient error: connection refused to L2 WS

### ISSUE THREAD

**Issue by ymittal** [taikoxyz/simple-taiko-node#167]
Hello! I'm having a lot of issues syncing my L2 to a local Holesky L1.

After doing `docker compose down && docker compose up -d && docker compose logs -f`, I managed to stop an error when L2 is just starting:
![image](https://github.com/taikoxyz/simple-taiko-node/assets/8350076/b54efd72-aca5-4fb0-90dd-7f9fa2b210a0)

```
L1_ENDPOINT_HTTP=http://LOCAL_VPS_IP:8545
L1_ENDPOINT_WS=ws://LOCAL_VPS_IP:8546
```
My `.env` file looks like this, but I'm also tried with `172.17.0.1` and `host.docker.internal` but to no avail.

**Comment by kylegranger** [comment]
For what it's worth, I also had a hard time connecting the Katla L2 to Holesky L1.  It looks like you're using the local IP address, which in the end, is also what ended up working for me.  Using `host.docker.internal` did not work.
```
L1_ENDPOINT_HTTP=http://10.132.0.8:8545
L1_ENDPOINT_WS=ws://10.132.0.8:8546
```
I had another issue (https://github.com/taikoxyz/simple-taiko-node/issues/165) that I solved by doing a `docker compose pull`.  You could try that.

**Comment by ymittal** [comment]
`docker compose pull` didn't do it for me. I'm curious, what cmd can I run (possible from inside L2 container) to ensure that L2 is able to talk to L1? I feel like that can help narrow down the cause.

**Comment by kylegranger** [comment]
Maybe try querying the latest block?  E.g., 
```
curl http://LOCAL_VPS_IP:8545/ -X POST -H "Content-Type: application/json" --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'
```

But this is only http.  Btw (you probably know this?), for the websocket `ws://` protocol, the nodes have to be on same system (if you don't go the route of secure connection + TLS + domain name).

**Comment by davidtaikocha** [comment]
Could u plz also show a screenshot of the CPU / memory usage of the node in grafana?

**Comment by davidtaikocha** [comment]
Should have been fixed now
