### ISSUE TITLE
Docker-Compose command not running

### ISSUE THREAD

**Issue by sreyom31** [taikoxyz/simple-taiko-node#169]
After attaching tmux session and cd simple-taiko-node. 
sudo docker-compose up -d giving error

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.l2_execution_engine: 'pull_policy'
Unsupported config option for services.taiko_client_driver: 'pull_policy'
Unsupported config option for services.taiko_client_proposer: 'pull_policy'
Unsupported config option for services.taiko_client_prover_relayer: 'pull_policy'
Unsupported config option for services.zkevm_chain_prover_rpcd: 'pull_policy'

<img width="579" alt="Screenshot 2024-01-24 at 4 10 50 PM" src="https://github.com/taikoxyz/simple-taiko-node/assets/71867762/d1bf10a3-5934-4aa3-8280-a6e8b02f4283">

**Comment by papadritta** [comment]
1. Ensure, that you have Docker Compose version 1.27.0 or later installed. You can check your version with `docker-compose --version` If you have an older version, update it. You can do it with your package manager.
2. Check `docker-compose.yml` there are no indentations or other syntactical errors.
