### ISSUE TITLE
invalid JWT secret file

### ISSUE THREAD

**Issue by benjiqq** [taikoxyz/simple-taiko-node#175]
after ```sudo docker compose up -d```

getting this in the logs

```
invalid JWT secret file: open /data/taiko-geth/geth/jwtsecret: no such file or directory
taiko_client_driver-1          | websocket: bad handshake (HTTP status 404 Not Found)
```

relates to this argument passed in

https://github.com/taikoxyz/simple-taiko-node/blob/main/script/start-driver.sh#L12

**Comment by davidtaikocha** [comment]
Plz check: https://docs.taiko.xyz/guides/run-a-taiko-node/#troubleshooting
