### ISSUE TITLE
I can't start the Taiko Node with a Local Holesky RPC

### ISSUE THREAD

**Issue by Beamaccount** [taikoxyz/simple-taiko-node#179]
Hi, i'm trying to start a Taiko Node with a VPC with a Holesky Node with Archive activated.
i receive in the different test i made those error from the Taiko Node:
taiko_client_driver-1          | dial tcp 192.168.160.1:8546: i/o timeout
or
error with RPC endpoint: node (ws://192.168.160.1:8546) must be archive node

what i can do? the Holesky node have activated the ARCHIVE_NODE=true.

thanks

**Comment by papadritta** [comment]
- Be sure that your `Holesky node` is completely in sync with the blockchain. You can use the `Holesky L1 endpoint`, but it must point to an archive node to access the state trie beyond the last `128 blocks`.

- Check for any port conflicts. Execute `sudo lsof -i -P -n | grep -i LISTEN` to verify the availability of the ports you intend to use. 

- Go through your `.env` file carefully and confirm your configurations for `L1_ENDPOINT_HTTP= `and `L1_ENDPOINT_WS=`. Refer to the `.env.sample` file for possible guidance. Check your IP address with `wget -qO- eth0.me`.

- As an option you can choose any `Holesky RPC provider`, but your own `Local Holesky node` is typically advisable. This approach avoids potential rate limits imposed by third-party providers.

**Comment by Beamaccount** [comment]
thanks for the help. I've changed Local Holesky node framework and now i receive this error:

taiko_client_driver-1          | no contract code at given address
taiko_client_driver-1 exited with code 1

i continue to investigating

**Comment by papadritta** [comment]
It looks like your `Holesky node` isn't fully synced:
1. Check the head of the chain on the `Holesky` beacon chain [explorer](https://holesky.beaconcha.in/blocks)
2. Check your eth node with `Graphana` dashboard with `Geth`and `Lighthouse`
3. When you settled up your Holesky node, you did it as  `non-root` user. Make sure you give for `User` the necessary permission and add to the Docker group.

**Comment by davidtaikocha** [comment]
> thanks for the help. I've changed Local Holesky node framework and now i receive this error:
> 
> taiko_client_driver-1 | no contract code at given address taiko_client_driver-1 exited with code 1
> 
> i continue to investigating

Looks like your holesky node is not fully synced.
