### ISSUE TITLE
Node working properly  but to view the status of node is not gud 

### ISSUE THREAD

**Issue by rajatj86** [taikoxyz/simple-taiko-node#180]
sometime when we try to watch the node status is not working properly 
![image](https://github.com/taikoxyz/simple-taiko-node/assets/85836532/c2231772-6765-4895-80a9-1c96fedcfc1f)

**Comment by haylas** [comment]
Sometime*

**Comment by zebroghosh** [comment]
sometimes , the node status is not working properly

**Comment by ramshazz** [comment]
It could be due to congestion and network issues, Please try again at a different time should work. This is normal.

**Comment by davidtaikocha** [comment]
We are using the geth metrics, so if the node is working properly and sometimes the dashboard is not good, can report an issue to go-ethereum :)
