### ISSUE TITLE
Feature Request : Enable websockets for public RPC

### ISSUE THREAD

**Issue by muskbuster** [taikoxyz/simple-taiko-node#183]
Current public RPC does not have ws endpoint and hence can't use subscriptions and event listeners. Current solution is running a local RPC. Dedicated provider 1RPC does not provide WSS either

**Comment by haylas** [comment]
agree++

**Comment by ramshazz** [comment]
Yeah good point, I think team should look into this

**Comment by davidtaikocha** [comment]
I think it's enabled? https://github.com/taikoxyz/simple-taiko-node/blob/main/.env.sample#L7
