### ISSUE TITLE
using different HTTPS and WS ports

### ISSUE THREAD

**Issue by kegdeg** [taikoxyz/simple-taiko-node#186]
Running a local holesky node, changed the HTTP port from 8545 to 8945 and the WS port from 8546 to 8946 (port 8545 is already taken). The problem is running the taiko node. Changed the ports in the .env file. I can log in to grafana and there is some traffic and peer connections but no chain activity.

docker compose logs 
prometheus-1  | ts=2024-02-09T02:06:50.524Z caller=main.go:544 level=info msg="No time or size retention was set so using the default time retention" duration=15d
prometheus-1  | ts=2024-02-09T02:06:50.526Z caller=main.go:588 level=info msg="Starting Prometheus Server" mode=server version="(version=2.49.1, branch=HEAD, revision=43e14844a33b65e2a396e3944272af8b3a494071)"
prometheus-1  | ts=2024-02-09T02:06:50.526Z caller=main.go:593 level=info build_context="(go=go1.21.6, platform=linux/amd64, user=root@6d5f4c649d25, date=20240115-16:58:43, tags=netgo,builtinassets,stringlabels)"
prometheus-1  | ts=2024-02-09T02:06:50.526Z caller=main.go:594 level=info host_details="(Linux 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 9b0deedf7196 (none))"
prometheus-1  | ts=2024-02-09T02:06:50.526Z caller=main.go:595 level=info fd_limits="(soft=1048576, hard=1048576)"
prometheus-1  | ts=2024-02-09T02:06:50.526Z caller=main.go:596 level=info vm_limits="(soft=unlimited, hard=unlimited)"
prometheus-1  | ts=2024-02-09T02:06:50.531Z caller=web.go:565 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
prometheus-1  | ts=2024-02-09T02:06:50.532Z caller=main.go:1039 level=info msg="Starting TSDB ..."
prometheus-1  | ts=2024-02-09T02:06:50.535Z caller=tls_config.go:274 level=info component=web msg="Listening on" address=[::]:9090
prometheus-1  | ts=2024-02-09T02:06:50.536Z caller=tls_config.go:277 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
prometheus-1  | ts=2024-02-09T02:06:50.560Z caller=head.go:606 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
prometheus-1  | ts=2024-02-09T02:06:50.567Z caller=head.go:687 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=6.631593ms
prometheus-1  | ts=2024-02-09T02:06:50.568Z caller=head.go:695 level=info component=tsdb msg="Replaying WAL, this may take a while"
prometheus-1  | ts=2024-02-09T02:06:50.627Z caller=head.go:766 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=3
prometheus-1  | ts=2024-02-09T02:06:50.632Z caller=head.go:766 level=info component=tsdb msg="WAL segment loaded" segment=1 maxSegment=3
prometheus-1  | ts=2024-02-09T02:06:50.661Z caller=head.go:766 level=info component=tsdb msg="WAL segment loaded" segment=2 maxSegment=3
prometheus-1  | ts=2024-02-09T02:06:50.661Z caller=head.go:766 level=info component=tsdb msg="WAL segment loaded" segment=3 maxSegment=3
prometheus-1  | ts=2024-02-09T02:06:50.661Z caller=head.go:803 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=131.441µs wal_replay_duration=93.196189ms wbl_replay_duration=271ns total_replay_duration=100.408213ms
prometheus-1  | ts=2024-02-09T02:06:50.665Z caller=main.go:1060 level=info fs_type=EXT4_SUPER_MAGIC
prometheus-1  | ts=2024-02-09T02:06:50.665Z caller=main.go:1063 level=info msg="TSDB started"
prometheus-1  | ts=2024-02-09T02:06:50.665Z caller=main.go:1064 level=debug msg="TSDB options" MinBlockDuration=2h MaxBlockDuration=1d12h MaxBytes=0B NoLockfile=false RetentionDuration=15d WALSegmentSize=0B WALCompression=true
prometheus-1  | ts=2024-02-09T02:06:50.665Z caller=main.go:1245 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
prometheus-1  | ts=2024-02-09T02:06:50.668Z caller=manager.go:194 level=debug component="discovery manager scrape" msg="Starting provider" provider=static/0 subs=[geth]
prometheus-1  | ts=2024-02-09T02:06:50.668Z caller=manager.go:212 level=debug component="discovery manager scrape" msg="Discoverer channel closed" provider=static/0
prometheus-1  | ts=2024-02-09T02:06:50.668Z caller=manager.go:194 level=debug component="discovery manager notify" msg="Starting provider" provider=static/0 subs=[config-0]
prometheus-1  | ts=2024-02-09T02:06:50.669Z caller=manager.go:212 level=debug component="discovery manager notify" msg="Discoverer channel closed" provider=static/0
prometheus-1  | ts=2024-02-09T02:06:50.669Z caller=main.go:1282 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=3.683601ms db_storage=65.881µs remote_storage=2.344µs web_handler=970ns query_engine=1.63µs scrape=2.405806ms scrape_sd=318.102µs notify=211.81µs notify_sd=165.619µs rules=3.781µs tracing=23.725µs
prometheus-1  | ts=2024-02-09T02:06:50.669Z caller=main.go:1024 level=info msg="Server is ready to receive web requests."
prometheus-1  | ts=2024-02-09T02:06:50.669Z caller=manager.go:146 level=info component="rule manager" msg="Starting rule manager..."
taiko_client_driver-1  | Post "http://172.18.0.1:8946": dial tcp 172.18.0.1:8946: i/o timeout
taiko_client_driver-1  | Post "http://172.18.0.1:8946": dial tcp 172.18.0.1:8946: i/o timeout
taiko_client_driver-1  | Post "http://172.18.0.1:8946": dial tcp 172.18.0.1:8946: i/o timeout
taiko_client_driver-1  | Post "http://172.18.0.1:8946": dial tcp 172.18.0.1:8946: i/o timeout
taiko_client_driver-1  | Post "http://172.18.0.1:8946": dial tcp 172.18.0.1:8946: i/o timeout
taiko_client_driver-1  | Post "http://172.18.0.1:8946": dial tcp 172.18.0.1:8946: i/o timeout
taiko_client_driver-1  | Post "http://172.18.0.1:8946": dial tcp 172.18.0.1:8946: i/o timeout
taiko_client_proposer-1  | PROPOSER IS DISABLED
l2_execution_engine-1    | INFO [02-09|02:06:49.131] Enabling metrics collection
l2_execution_engine-1    | INFO [02-09|02:06:49.131] Enabling stand-alone metrics HTTP endpoint address=0.0.0.0:6060
l2_execution_engine-1    | INFO [02-09|02:06:49.131] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics
l2_execution_engine-1    | INFO [02-09|02:06:49.142] Maximum peer count                       ETH=50 total=50
l2_execution_engine-1    | INFO [02-09|02:06:49.152] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
l2_execution_engine-1    | INFO [02-09|02:06:49.157] Enabling recording of key preimages since archive mode is used
l2_execution_engine-1    | WARN [02-09|02:06:49.157] Disabled transaction unindexing for archive node
l2_execution_engine-1    | INFO [02-09|02:06:49.158] Set global gas cap                       cap=50,000,000
l2_execution_engine-1    | INFO [02-09|02:06:49.165] Initializing the KZG library             backend=gokzg
l2_execution_engine-1    | INFO [02-09|02:06:49.258] Allocated trie memory caches             clean=307.00MiB dirty=0.00B
l2_execution_engine-1    | INFO [02-09|02:06:49.259] Using pebble as the backing database
l2_execution_engine-1    | INFO [02-09|02:06:49.259] Allocated cache and file handles         database=/data/taiko-geth/geth/chaindata cache=512.00MiB handles=524,288
l2_execution_engine-1    | INFO [02-09|02:06:49.271] Opened ancient database                  database=/data/taiko-geth/geth/chaindata/ancient/chain readonly=false
l2_execution_engine-1    | INFO [02-09|02:06:49.272] State scheme set to already existing     scheme=hash
l2_execution_engine-1    | INFO [02-09|02:06:49.276] Initialising Ethereum protocol           network=167,008 dbversion=8
l2_execution_engine-1    | INFO [02-09|02:06:49.286] 
l2_execution_engine-1    | INFO [02-09|02:06:49.286] ---------------------------------------------------------------------------------------------------------------------------------------------------------
l2_execution_engine-1    | INFO [02-09|02:06:49.286] Chain ID:  167008 (Taiko Alpha-6 L2 (Katla))
l2_execution_engine-1    | INFO [02-09|02:06:49.286] Consensus: Taiko
l2_execution_engine-1    | INFO [02-09|02:06:49.286] 
l2_execution_engine-1    | INFO [02-09|02:06:49.286] Pre-Merge hard forks (block based):
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Homestead:                   #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Tangerine Whistle (EIP 150): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Spurious Dragon/1 (EIP 155): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Spurious Dragon/2 (EIP 158): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Byzantium:                   #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Constantinople:              #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Petersburg:                  #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Istanbul:                    #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Berlin:                      #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - London:                      #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286] 
l2_execution_engine-1    | INFO [02-09|02:06:49.286] Merge configured:
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Hard-fork specification:    https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Network known to be merged: true
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Total terminal difficulty:  0
l2_execution_engine-1    | INFO [02-09|02:06:49.286] 
l2_execution_engine-1    | INFO [02-09|02:06:49.286] Post-Merge hard forks (timestamp based):
l2_execution_engine-1    | INFO [02-09|02:06:49.286]  - Shanghai:                    @0          (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md)
l2_execution_engine-1    | INFO [02-09|02:06:49.286] 
l2_execution_engine-1    | INFO [02-09|02:06:49.286] ---------------------------------------------------------------------------------------------------------------------------------------------------------
l2_execution_engine-1    | INFO [02-09|02:06:49.286] 
grafana-1                | logger=local.finder t=2024-02-09T02:06:51.656090384Z level=warn msg="Skipping finding plugins as directory does not exist" path=/usr/share/grafana/plugins-bundled
grafana-1                | logger=provisioning.plugins t=2024-02-09T02:06:51.763845829Z level=error msg="Failed to read plugin provisioning files from directory" path=/etc/grafana/custom/provisioning/plugins error="open /etc/grafana/custom/provisioning/plugins: no such file or directory"
grafana-1                | logger=provisioning.notifiers t=2024-02-09T02:06:51.763921702Z level=error msg="Can't read alert notification provisioning files from directory" path=/etc/grafana/custom/provisioning/notifiers error="open /etc/grafana/custom/provisioning/notifiers: no such file or directory"
grafana-1                | logger=provisioning.alerting t=2024-02-09T02:06:51.763954367Z level=error msg="can't read alerting provisioning files from directory" path=/etc/grafana/custom/provisioning/alerting error="open /etc/grafana/custom/provisioning/alerting: no such file or directory"
l2_execution_engine-1    | INFO [02-09|02:06:49.287] Loaded most recent local block           number=0 hash=7be2de..ea680e td=0 age=54y10mo3w
l2_execution_engine-1    | INFO [02-09|02:06:49.287] Initialized transaction indexer          range="entire chain"
l2_execution_engine-1    | INFO [02-09|02:06:49.288] Loaded local transaction journal         transactions=0 dropped=0
l2_execution_engine-1    | INFO [02-09|02:06:49.288] Regenerated local transaction journal    transactions=0 accounts=0
l2_execution_engine-1    | INFO [02-09|02:06:49.355] Chain post-merge, sync via beacon client
l2_execution_engine-1    | INFO [02-09|02:06:49.356] Gasprice oracle is ignoring threshold set threshold=2
l2_execution_engine-1    | WARN [02-09|02:06:49.360] Engine API enabled                       protocol=eth
l2_execution_engine-1    | INFO [02-09|02:06:49.360] Starting peer-to-peer node               instance=Geth/v1.13.11-stable/linux-amd64/go1.21.7
l2_execution_engine-1    | INFO [02-09|02:06:49.478] New local node record                    seq=1,707,433,979,340 id=85f496e8d1c5231a ip=127.0.0.1 udp=30303 tcp=30303
l2_execution_engine-1    | INFO [02-09|02:06:49.481] IPC endpoint opened                      url=/data/taiko-geth/geth.ipc
l2_execution_engine-1    | INFO [02-09|02:06:49.481] Started P2P networking                   self=enode://8be029de9b1046a48f6f38bcd1ffc69c36d6062d1d25da75aaa83d20821938f2033fba6cafeb5fd113fa3a854ac81bab71d57aa25ad70f34f4f47c3914d63a02@127.0.0.1:30303
l2_execution_engine-1    | INFO [02-09|02:06:49.483] Loaded JWT secret file                   path=/data/taiko-geth/geth/jwtsecret crc32=0xe45f4da7
l2_execution_engine-1    | INFO [02-09|02:06:49.484] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors= vhosts=*
l2_execution_engine-1    | INFO [02-09|02:06:49.484] WebSocket enabled                        url=ws://[::]:8546
l2_execution_engine-1    | INFO [02-09|02:06:49.485] WebSocket enabled                        url=ws://[::]:8551
l2_execution_engine-1    | INFO [02-09|02:06:49.485] HTTP server started                      endpoint=[::]:8551 auth=true  prefix= cors=localhost vhosts=*
l2_execution_engine-1    | INFO [02-09|02:06:52.159] New local node record                    seq=1,707,433,979,341 id=85f496e8d1c5231a ip=173.212.251.148 udp=30303 tcp=30303
l2_execution_engine-1    | INFO [02-09|02:06:59.789] Looking for peers                        peercount=2 tried=191 static=0
l2_execution_engine-1    | WARN [02-09|02:07:24.362] Post-merge network, but no beacon client seen. Please launch one to follow the chain!

**Comment by haylas** [comment]
You can 

Check and update connectivity.
Verify configuration in .env file.
Review logs, check for errors.
Check Grafana metrics, monitor chain activity.
Monitor peer connections, insufficient connections can cause issues.
Restart, for full application of configuration changes.
Seek community support, others may help with similar issues.
