### ISSUE TITLE
View my node status

### ISSUE THREAD

**Issue by rajatj86** [taikoxyz/simple-taiko-node#189]
How can i view the status of my node like the data

**Comment by haylas** [comment]
To view the status of your node and data, you typically need to access the Sharduem node's interface or dashboard. Here's a general guide on how you can do this:

Accessing the Node Interface: Typically, Sharduem nodes provide a web-based interface or dashboard where you can view various statistics and status updates. You can access this interface by entering the IP address or domain name of your node into a web browser. This interface often requires authentication, so make sure you have the necessary credentials.

Dashboard Features: Once you're logged in, you should see various sections or tabs displaying information about your node's status. This information may include metrics such as block height, synchronization status, network connectivity, hardware resource usage, and more.

Monitoring Tools: Some Sharduem nodes also offer monitoring tools or integrations that allow you to track the performance and health of your node more closely. These tools might provide graphs, charts, and alerts for important metrics.

API Access: Additionally, some nodes offer API access, allowing you to programmatically retrieve data about your node's status. You can use this data to build custom monitoring solutions or integrate node status into your existing systems.

Community Resources: If you're having trouble accessing or interpreting the node status information, don't hesitate to reach out to the Sharduem community or support channels. They can provide guidance and assistance tailored to your specific situation.

By following these steps, you should be able to view the status of your Sharduem node and its data effectively.

**Comment by davidtaikocha** [comment]
Can check the dashboard: https://docs.taiko.xyz/guides/run-a-taiko-node/#6-verify-node-is-running
