### ISSUE TITLE
[suggest]declaim line sequence of shell is LF in windows

### ISSUE THREAD

**Issue by 24code** [taikoxyz/simple-taiko-node#198]
### Describe the bug

env
os: Windows 11 22631.3155
docker: Docker Desktop 4.28.0 (139021)

if line sequence of shell is CRLF, will report this error,
need modify to LF, it's work
<img width="558" alt="image" src="https://github.com/taikoxyz/simple-taiko-node/assets/5975695/13745d53-bd40-40bf-9662-dc77ad0b9626">

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
all scripts line sequence endings are LF already
