### ISSUE TITLE
Proposer not making right transaction

### ISSUE THREAD

**Issue by annanzubair** [taikoxyz/simple-taiko-node#212]
### Describe the bug

Proposer making wrong transaction of contract creation with empty data instead of ProposeBlock Method

### Steps to reproduce

[Proposer is making transactions like this](https://holesky.etherscan.io/tx/0xc3aaf01236edf0647151fc1f32940121d73b794d5b54806fa26805ad951256bb)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Don't think its possible in current codebase :)
