### ISSUE TITLE
engine, driver and proposer always restart

### ISSUE THREAD

**Issue by huangsiyuan924** [taikoxyz/simple-taiko-node#216]
### Describe the bug

`docker ps`
![image](https://github.com/taikoxyz/simple-taiko-node/assets/47273722/b7ca0db3-ca75-4e93-8dec-9e8bda95eeaf)
`docker logs simple-taiko-node-taiko_client_driver-1`
![image](https://github.com/taikoxyz/simple-taiko-node/assets/47273722/67e6009d-6531-4ea3-95a8-dd56e2fec2fb)
`docker logs simple-taiko-node-taiko_client_proposer-1`
![image](https://github.com/taikoxyz/simple-taiko-node/assets/47273722/8601f76f-448c-4b4c-8c47-e707d9378fae)
`docker logs -f simple-taiko-node-l2_execution_engine-1`
![image](https://github.com/taikoxyz/simple-taiko-node/assets/47273722/4182940a-edbc-46e5-95d8-b4e0c3374af9)

my vps system: centos7.9

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
@huangsiyuan924 https://github.com/bnb-chain/bsc/issues/1521#issuecomment-1521025294 this seems like a similar thing, could you try this fix and retry?

**Comment by huangsiyuan924** [comment]
> docker logs -f simple-taiko-node-l2_execution_engine-1

Now the geth container is still restarting, and the error is: invalid value "shielded-expedition.88f17d1d14" for flag -networkid: parse error

**Comment by huangsiyuan924** [comment]
> @huangsiyuan924 [bnb-chain/bsc#1521 (comment)](https://github.com/bnb-chain/bsc/issues/1521#issuecomment-1521025294) this seems like a similar thing, could you try this fix and retry?

Now the geth container is still restarting, and the error is: invalid value "shielded-expedition.88f17d1d14" for flag -networkid: parse error
