### ISSUE TITLE
Error: Failed to decode tx list: beacon client not found

### ISSUE THREAD

**Issue by bgurning** [taikoxyz/simple-taiko-node#218]
### Describe the bug

taiko_client_driver produce error: block batch iterator callback error, error:"failed to decode tx list: beacon client not found"

The log:
taiko_client_driver-1  | INFO [04-27|17:10:48.688] New BlockProposed event                  l1Height=1,431,022 l1Hash=e9e76c..a1a029 blockID=57035 removed=false
taiko_client_driver-1  | INFO [04-27|17:10:48.999] New BlockProposed event                  l1Height=1,431,024 l1Hash=e4cf7b..cf8b3f blockID=57036 removed=false
taiko_client_driver-1  | INFO [04-27|17:10:49.310] Failed to get blobs from beacon, try to use blob server. error="beacon client not found"
taiko_client_driver-1  | INFO [04-27|17:10:49.310] No blob server endpoint set
taiko_client_driver-1  | ERROR[04-27|17:10:49.310] Block batch iterator callback error      error="failed to decode tx list: beacon client not found"

### Steps to reproduce

docker compose --profile l2_execution_engine up && docker compose --profile proposer up && docker compose --profile prover up

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
`L1_BEACON_HTTP=...` is required.
