### ISSUE TITLE
Add error handing for scripts

### ISSUE THREAD

**Issue by richardgreg** [taikoxyz/simple-taiko-node#219]
### Describe the feature request

The scripts could be made more robust by implementing better error handling. This would involve checking the return values of commands and taking appropriate actions, such as printing helpful error messages and exiting gracefully.

If the team would welcome this, I'd be happy to work on it.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Plz feel free to open a PR :)

**Comment by RogerLamTd** [comment]
closing as stale, please reopen if necessary
