### ISSUE TITLE
ERROR: Failed to request proof   |  Task XX "panicked" 

### ISSUE THREAD

**Issue by StoneMac65** [taikoxyz/simple-taiko-node#220]
### Describe the bug

There is an issue with  prover and it will not go away unless you restart the "Prover" in simple-taiko-node

it also reflect on Raiko logs too

command used 

` sudo docker compose down taiko_client_prover_relayer   &&  sudo docker compose up  taiko_client_prover_relayer -d`

### **taiko_client_prover_relayer-1** Logs

```
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:27.277] Failed to request proof                  height=60987 error="task 7746 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:28.033] Failed to request proof                  height=60675 error="task 7748 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:28.462] Failed to request proof                  height=60814 error="task 7750 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:30.423] Failed to request proof                  height=60993 error="task 7752 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:32.764] Failed to request proof                  height=61129 error="task 7754 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:33.191] Failed to request proof                  height=61122 error="task 7756 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:37.511] Failed to request proof                  height=60987 error="task 7758 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:38.251] Failed to request proof                  height=60675 error="task 7760 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:38.695] Failed to request proof                  height=60814 error="task 7762 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:40.642] Failed to request proof                  height=60993 error="task 7764 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:42.985] Failed to request proof                  height=61129 error="task 7766 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:43.409] Failed to request proof                  height=61122 error="task 7768 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
taiko_client_prover_relayer-1  | `ERROR`[04-29|00:56:47.732] Failed to request proof                  height=60987 error="task 7770 panicked" endpoint=XXXXXXXXXXXXXXXXXXXXXXXX
```

**### Raiko Logs**

```
raiko  |     0: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  |     1: client `error` (Connect)
raiko  |     2: dns `error`: failed to lookup address information: Temporary failure in name resolution
raiko  |     3: failed to lookup address information: Temporary failure in name resolution
raiko  | Fetching block data...`Error`: task 16656 panicked
raiko  | # Generating proof for block 60993 on taiko_a7
raiko  | Generating input...
raiko  | thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:50:58:
raiko  | called `Result::unwrap()` on an `Err` value: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  | 
raiko  | Caused by:
raiko  |     0: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  |     1: client `error` (Connect)
raiko  |     2: dns `error`: failed to lookup address information: Temporary failure in name resolution
raiko  |     3: failed to lookup address information: Temporary failure in name resolution
raiko  | Fetching block data...`Error`: task 16658 panicked
raiko  | # Generating proof for block 61129 on taiko_a7
raiko  | Generating input...
raiko  | thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:50:58:
raiko  | called `Result::unwrap()` on an `Err` value: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  | 
raiko  | Caused by:
raiko  |     0: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  |     1: client `error` (Connect)
raiko  |     2: dns `error`: failed to lookup address information: Temporary failure in name resolution
raiko  |     3: failed to lookup address information: Temporary failure in name resolution
raiko  | Fetching block data...`Error`: task 16660 panicked
raiko  | # Generating proof for block 61122 on taiko_a7
raiko  | Generating input...
raiko  | thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:50:58:
raiko  | called `Result::unwrap()` on an `Err` value: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  | 
raiko  | Caused by:
raiko  |     0: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  |     1: client `error` (Connect)
raiko  |     2: dns `error`: failed to lookup address information: Temporary failure in name resolution
raiko  |     3: failed to lookup address information: Temporary failure in name resolution
raiko  | Fetching block data...`Error`: task 16662 panicked
raiko  | # Generating proof for block 60987 on taiko_a7
raiko  | Generating input...
raiko  | thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:50:58:
raiko  | called `Result::unwrap()` on an `Err` value: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  | 
raiko  | Caused by:
raiko  |     0: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  |     1: client `error` (Connect)
raiko  |     2: dns `error`: failed to lookup address information: Temporary failure in name resolution
raiko  |     3: failed to lookup address information: Temporary failure in name resolution
raiko  | Fetching block data...`Error`: task 16664 panicked
raiko  | # Generating proof for block 60675 on taiko_a7
raiko  | Generating input...
raiko  | thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:50:58:
raiko  | called `Result::unwrap()` on an `Err` value: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  | 
raiko  | Caused by:
raiko  |     0: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  |     1: client `error` (Connect)
raiko  |     2: dns `error`: failed to lookup address information: Temporary failure in name resolution
raiko  |     3: failed to lookup address information: Temporary failure in name resolution
raiko  | Fetching block data...`Error`: task 16666 panicked
raiko  | # Generating proof for block 60814 on taiko_a7
raiko  | Generating input...
raiko  | thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:50:58:
raiko  | called `Result::unwrap()` on an `Err` value: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  | 
raiko  | Caused by:
raiko  |     0: `error` sending request for url (http://l2_execution_engine:8545/)
raiko  |     1: client `error` (Connect)
raiko  |     2: dns `error`: failed to lookup address information: Temporary failure in name resolution
raiko  |     3: failed to lookup address information: Temporary failure in name resolution
raiko  | Fetching block data...`Error`: task 16668 panicked
```

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by johntaiko** [comment]
`l2_execution_engine` is not a validated domain for raiko, do you use l2 node behind docker compose?

**Comment by StoneMac65** [comment]
> `l2_execution_engine` is not a validated domain for raiko, do you use l2 node behind docker compose?

I use taiko node on separate server and point it to SGX machine. simple taiko node and local Holesky are on same server, Raiko is in another serverit works perfectly and proved many blocks so far,  since two days ago while node remains idle because of 0 ttkoh balance this error comes up

**Comment by davidtaikocha** [comment]
> > `l2_execution_engine` is not a validated domain for raiko, do you use l2 node behind docker compose?
> 
> I use taiko node on separate server and point it to SGX machine. simple taiko node and local Holesky are on same server, Raiko is in another serverit works perfectly and proved many blocks so far, since two days ago while node remains idle because of 0 ttkoh balance this error comes up

noted this issue, we will push a PR here to fix this domain issue.

**Comment by StoneMac65** [comment]
> > > `l2_execution_engine` is not a validated domain for raiko, do you use l2 node behind docker compose?
> > 
> > 
> > I use taiko node on separate server and point it to SGX machine. simple taiko node and local Holesky are on same server, Raiko is in another serverit works perfectly and proved many blocks so far, since two days ago while node remains idle because of 0 ttkoh balance this error comes up
> 
> noted this issue, we will push a PR here to fix this domain issue.

great. thanks

**Comment by quangtuyen88** [comment]
Hello @RogerLamTd and @davidtaikocha  can you mention before implement a fix on Discord for that? 
I don't wanna my TTKOh to get slashed with breaking changes.

**Comment by davidtaikocha** [comment]
> Hello @RogerLamTd and @davidtaikocha can you mention before implement a fix on Discord for that? I don't wanna my TTKOh to get slashed with breaking changes. I will stop my prover during this time. Thanks

sure, @RogerLamTd will

**Comment by 0xm51** [comment]
In addition, after a simple node restart today I saw this in prover logs :
```
taiko_client_prover_relayer-1  | ERROR[04-29|08:04:19.342] Failed to request proof                  height=60987 error="Post \"host.docker.internal:8080\": unsupported protocol scheme \"host.docker.internal\"" endpoint=host.docker.internal:8080
```
So I tested to restart by adding http scheme in `SGX_RAIKO_HOST` and felt exactly in this `task XX panicked` issue here mentioned

**Comment by StoneMac65** [comment]
> In addition, after a simple node restart today I saw this in prover logs :
> 
> ```
> taiko_client_prover_relayer-1  | ERROR[04-29|08:04:19.342] Failed to request proof                  height=60987 error="Post \"host.docker.internal:8080\": unsupported protocol scheme \"host.docker.internal\"" endpoint=host.docker.internal:8080
> ```
> 
> So I tested to restart by adding http scheme in `SGX_RAIKO_HOST` and felt exactly in this `task XX panicked` issue here mentioned

Oh you are running both on same server. I think its basically the same issue

**Comment by 0xm51** [comment]
> > In addition, after a simple node restart today I saw this in prover logs :
> > ```
> > taiko_client_prover_relayer-1  | ERROR[04-29|08:04:19.342] Failed to request proof                  height=60987 error="Post \"host.docker.internal:8080\": unsupported protocol scheme \"host.docker.internal\"" endpoint=host.docker.internal:8080
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I tested to restart by adding http scheme in `SGX_RAIKO_HOST` and felt exactly in this `task XX panicked` issue here mentioned
> 
> Oh you are running both on same server. I think its basically the same issue

Yes, same issue with raiko and stn on same server

**Comment by RogerLamTd** [comment]
@StoneMac65 @quangtuyen88 @0xm51 updated stn! please set your public ip in the .env as instructed and it should work

**Comment by quangtuyen88** [comment]
Hello @RogerLamTd That IP use for callback from Raiko to Taiko node ? Do I need to set the port for that?

**Comment by RogerLamTd** [comment]
> Hello @RogerLamTd That IP use for callback from Raiko to Taiko node ? Do I need to set the port for that?

Just the IP

**Comment by quangtuyen88** [comment]
Because i have changed this port `PORT_L2_EXECUTION_ENGINE_HTTP=8547`
Is there any issue with this ?

**Comment by RogerLamTd** [comment]
> Because i have changed this port `PORT_L2_EXECUTION_ENGINE_HTTP=8547` Is there any issue with this ?

No, if you changed it in the .env file then the script should use that port; there should be no issue.

**Comment by quangtuyen88** [comment]
Ok. Thanks
