### ISSUE TITLE
Failed to clean stale beacon headers     err="filled header below beacon header tail: 45987 < 67388"

### ISSUE THREAD

**Issue by lucajj3** [taikoxyz/simple-taiko-node#222]
### Describe the bug

Failed to clean stale beacon headers.

I don't think there is a solution at the moment other than having to rebuild the docker

### Steps to reproduce

1) If node isnt sync and stopped node ( i have editeded .env too), 
2) run node 
you may have this error:
 Beacon backfilling failed                err="syncing canceled (requested)"
 ERROR Failed to clean stale beacon headers     err="filled header below beacon header tail: 45987 < 67392"

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by StoneMac65** [comment]
same here. tested several endpoints 

```
l2_execution_engine-1    | INFO [05-01|07:08:51.150] Restarting sync cycle                    reason="chain gapped, head: 70168, newHead: 70170"
l2_execution_engine-1    | ERROR[05-01|07:08:51.150] Failed to clean stale beacon headers     err="filled header below beacon header tail: 70002 < 70168"
```

**Comment by StoneMac65** [comment]
I installed Nimbus for local Holesky beacon node. It didnt solve syncing speed issue still very slow and not usabe

![image](https://github.com/taikoxyz/simple-taiko-node/assets/103312943/0eb25f95-d77e-4c2e-b624-633778815da5)

**Comment by amis13** [comment]
###Solved:
I'm using my own beacon RPC by port 5052

###Open REST port:
add in your Holesky .env:
`COMPOSE_FILE......:cl-shared.yml`

###STEPS
update your holesky node: sudo ./ethd update
Add the new TAG in Holesky .env: `TRAEFIK_TAG=v3.0`
Restart: sudo ./ethd up

Add: `enode://0b310c7dcfcf45ef32dde60fec274af88d52c7f0fb6a7e038b14f5f7bb7d72f3ab96a59328270532a871db988a0bcf57aa9258fa8a80e8e553a7bb5abd77c40d@167.235.249.45:30303` to BOOT_NODES in taiko node .env
Restart and delete old images: 
`docker compose --profile l2_execution_engine down -v && docker rmi -f $(docker images -aq) && docker compose --profile l2_execution_engine up -d`

**Comment by lucajj3** [comment]
> # Solved:
> I'm using my own beacon RPC by port 5052
> 
> ### STEPS
> Open REST port: add in your Holesky .env: `COMPOSE_FILE=......:cl-shared.yml`
> 
> update your holesky node: `sudo ./ethd update` Add the new TAG in Holesky .env: `TRAEFIK_TAG=v3.0` Restart: `sudo ./ethd up`
> 
> Add in taiko node .env: `BOOT_NODES=<enode://......>,enode://0b310c7dcfcf45ef32dde60fec274af88d52c7f0fb6a7e038b14f5f7bb7d72f3ab96a59328270532a871db988a0bcf57aa9258fa8a80e8e553a7bb5abd77c40d@167.235.249.45:30303`
> 
> You can add more separated by a "," without spaces, find how and more `BOOT_NODES` here: https://github.com/taikoxyz/simple-taiko-node/blob/main/.env.sample
> 
> and `L1_BEACON_HTTP=http://<YOUR_HOLESKY_NODE_IP>:5052`
> 
> Restart and delete old images: `docker compose --profile l2_execution_engine down -v && docker rmi -f $(docker images -aq) && docker compose --profile l2_execution_engine up -d`

solved? i dont use own beacon rpc node

**Comment by amis13** [comment]
> > # Solved:
> > I'm using my own beacon RPC by port 5052
> > ### STEPS
> > Open REST port: add in your Holesky .env: `COMPOSE_FILE=......:cl-shared.yml`
> > update your holesky node: `sudo ./ethd update` Add the new TAG in Holesky .env: `TRAEFIK_TAG=v3.0` Restart: `sudo ./ethd up`
> > Add in taiko node .env: `BOOT_NODES=<enode://......>,enode://0b310c7dcfcf45ef32dde60fec274af88d52c7f0fb6a7e038b14f5f7bb7d72f3ab96a59328270532a871db988a0bcf57aa9258fa8a80e8e553a7bb5abd77c40d@167.235.249.45:30303`
> > You can add more separated by a "," without spaces, find how and more `BOOT_NODES` here: https://github.com/taikoxyz/simple-taiko-node/blob/main/.env.sample
> > and `L1_BEACON_HTTP=http://<YOUR_HOLESKY_NODE_IP>:5052`
> > Restart and delete old images: `docker compose --profile l2_execution_engine down -v && docker rmi -f $(docker images -aq) && docker compose --profile l2_execution_engine up -d`
> 
> solved? i dont use own beacon rpc node

yes it's fixed.
Simple, follow this: https://github.com/taikoxyz/simple-taiko-node/issues/222#issuecomment-2089016632 and use it,
or try with your public RPC but having our own nodes, I see it as something quite unnecessary...

**Comment by 0xm51** [comment]
Thanks for [workaround](https://github.com/taikoxyz/simple-taiko-node/issues/222#issuecomment-2088689280)
Worked for me and L2 synced in 8min only !

**Comment by mask-pp** [comment]
> same here. tested several endpoints
> 
> ```
> l2_execution_engine-1    | INFO [05-01|07:08:51.150] Restarting sync cycle                    reason="chain gapped, head: 70168, newHead: 70170"
> l2_execution_engine-1    | ERROR[05-01|07:08:51.150] Failed to clean stale beacon headers     err="filled header below beacon header tail: 70002 < 70168"
> ```

Thanks for your feedback. I'm looking for the reason. This kind of problem will be very helpful for us to make the node more stable.

**Comment by mask-pp** [comment]
> I installed Nimbus for local Holesky beacon node. It didn't solve syncing speed. still very slow and not usable
> 
> ![image](https://private-user-images.githubusercontent.com/103312943/327150391-0eb25f95-d77e-4c2e-b624-633778815da5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzQ5NjksIm5iZiI6MTcxNDU3NDY2OSwicGF0aCI6Ii8xMDMzMTI5NDMvMzI3MTUwMzkxLTBlYjI1Zjk1LWQ3N2UtNGMyZS1iNjI0LTYzMzc3ODgxNWRhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxNDQ0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2ZmNTg4ZDdmMjMyNGJjNWRkMWRiZGNlMTBkZGExMDk5OGJjYTYzOGY0YmZjMTRmNGFkZDViNWQyOTUwMjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3FTwswK572g-3PbTIz7-88PRymOVtFfMQa1RdSCdMsw)

You can try to start snap sync.

**Comment by lagunovsky** [comment]
@amis13 your bootnode is not working 🙂

original workaround working bootnode: 
```
enode://0b310c7dcfcf45ef32dde60fec274af88d52c7f0fb6a7e038b14f5f7bb7d72f3ab96a59328270532a871db988a0bcf57aa9258fa8a80e8e553a7bb5abd77c40d@167.235.249.45:30303
```

**Comment by StoneMac65** [comment]
> @amis13 your bootnode is not working 🙂
> 
> original workaround working bootnode:
> 
> ```
> enode://0b310c7dcfcf45ef32dde60fec274af88d52c7f0fb6a7e038b14f5f7bb7d72f3ab96a59328270532a871db988a0bcf57aa9258fa8a80e8e553a7bb5abd77c40d@167.235.249.45:30303
> ```

previous enode that @amis13 provided was working perfectly and still is if I'm not mistaken

**Comment by amis13** [comment]
> @amis13 your bootnode is not working 🙂
> 
> original workaround working bootnode (which I manage):
> 
> ```
> enode://0b310c7dcfcf45ef32dde60fec274af88d52c7f0fb6a7e038b14f5f7bb7d72f3ab96a59328270532a871db988a0bcf57aa9258fa8a80e8e553a7bb5abd77c40d@167.235.249.45:30303
> ```

Fixed, I've tested and you were right, the request port isn't the 30303, it's 30306:
`enode://1d3cbb450d07d0657c0636528a25b26232d1c9cf5b7fc2eec22a29b5bde58b9227cb88bca388d822f26662705221e77c07153bc3fc4cb06472d0e09e9208b9bc@77.237.244.179:30306`
