### ISSUE TITLE
Prover not working with panick mode on Raiko 

### ISSUE THREAD

**Issue by quangtuyen88** [taikoxyz/simple-taiko-node#226]
### Describe the bug

Prover just working and suddenly stop working with error on Raiko container : 

```
# Generating proof for block 79103 on taiko_a7
Generating input...
thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:44:56:
invalid rpc url: RelativeUrlWithoutBase
Error: task 9978 panicked
# Generating proof for block 79073 on taiko_a7
Generating input...
thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:44:56:
invalid rpc url: RelativeUrlWithoutBase
Error: task 9979 panicked
thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:44:56:
invalid rpc url: RelativeUrlWithoutBase
# Generating proof for block 80046 on taiko_a7
Generating input...
Error: task 9980 panicked
# Generating proof for block 78974 on taiko_a7
Generating input...
Error: task 9981 panicked
thread 'tokio-runtime-worker' panicked at host/src/preflight.rs:44:56:
invalid rpc url: RelativeUrlWithoutBase
```

for this env `TAIKO_NODE_IP=xx.xx.xx.xx` I input IP only without HTTP:// not sure if related to this issue.. because I only see above error after successful prove some proof
### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by quangtuyen88** [comment]
Hello @smtmfft . No it's not normal.. I got 16 successful prove transactions and failed at 17th transaction..Ii can confirm my RPC still working now.
Today I don't have that issue use same config. I just add HTTP:// for this env only `TAIKO_NODE_IP `

**Comment by quangtuyen88** [comment]
Just update i'm using my Holesksy node for RPC ( changed default port also) : 
```
L1_ENDPOINT_HTTP=http://xx.xx.xx.xx:8565
L1_ENDPOINT_WS=ws://xx.xx.xx.xx:8566
```

**Comment by smtmfft** [comment]
> Hello @smtmfft . No it's not normal.. I got 16 successful prove transactions and failed at 17th transaction..I can confirm my RPC still working now. Today I don't have that issue use same config. I just add HTTP:// for this env only `TAIKO_NODE_IP `

That's strange... as far as I know only the null entrypoint (especially the beacon one as we call it directly) could report error like these. Let me know if it happens again. Thanks!

**Comment by quangtuyen88** [comment]
> > Hello @smtmfft . No it's not normal.. I got 16 successful proof transactions and failed at the 17th transaction..I can confirm my RPC still working now. Today I don't have that issue using the same config. I just add HTTP:// for this env only `TAIKO_NODE_IP `
> 
> That's strange... as far as I know only the null entrypoint (especially the beacon one as we call it directly) could report errors like these. Let me know if it happens again. Thanks!

Hello.. I'm getting the same issue today: You can see with 6 propose transactions submitted it failed at the 6th transaction and 5 transactions were successful. 
![Screenshot 2024-05-05 at 16 27 53](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/2d076927-f3c0-4b9a-b4c5-9a8531b60add)


![Screenshot 2024-05-05 at 16 27 46](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/00083704-d96f-48d3-bb10-af2146369759)

log on Raiko container : 
```
Failed to fetch required data for block: builder error: relative URL without a base

Caused by:
    relative URL without a base
# Generating proof for block 89189 on taiko_a7
Generating input...
Fetching block data...
block.hash: 0x11b4b45d58ffcfaeb584fc89c566e4cd9dc7351228d76d96b02bb521ce178467
block.parent_hash: 0xbecef6c05432476ced880c968dd8165345b0cbe21f871e1cbed69547186bf947
block gas used: 7034949
block transactions: 46
anchor L1 block id: 1481163
anchor L1 state root: 0x17f9e44063f558f95b60c9f3e01a2ec86b18113e27ad0f176868b53145384127
l1_state_root_block hash: 0xeccf7b5bc6c9ada956e29fdc21ac345b6505376b4f572c28f9a5e04bd9df7441
blob active
thread 'tokio-runtime-worker' panicked at host/src/execution.rs:97:10:
Failed to fetch required data for block: builder error: relative URL without a base

Caused by:
    relative URL without a base
Error: task 4467 panicked
# Generating proof for block 89189 on taiko_a7
Generating input...
Fetching block data...
block.hash: 0x11b4b45d58ffcfaeb584fc89c566e4cd9dc7351228d76d96b02bb521ce178467
block.parent_hash: 0xbecef6c05432476ced880c968dd8165345b0cbe21f871e1cbed69547186bf947
block gas used: 7034949
block transactions: 46
anchor L1 block id: 1481163
anchor L1 state root: 0x17f9e44063f558f95b60c9f3e01a2ec86b18113e27ad0f176868b53145384127
l1_state_root_block hash: 0xeccf7b5bc6c9ada956e29fdc21ac345b6505376b4f572c28f9a5e04bd9df7441
blob active
thread 'tokio-runtime-worker' panicked at host/src/execution.rs:97:10:
Failed to fetch required data for block: builder error: relative URL without a base

Caused by:
    relative URL without a base
Error: task 4475 panicked
```

**Comment by quangtuyen88** [comment]
![Screenshot 2024-05-06 at 09 25 03](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/bd4fd373-d2f9-49de-98ad-236b98aab921)
Just sharing I'm tailing my log of my prover this time.. and after successful prove some proofs it will fail

**Comment by smtmfft** [comment]
I can only reproduce this by send incorrect beaconRpc like
```
beaconRpc="/" or ""
```
Then
```
thread 'tokio-runtime-worker' panicked at host/src/execution.rs:114:10:
Failed to fetch required data for block: builder error: relative URL without a base

Caused by:
    relative URL without a base
```

Can you try printing the request out?
or you can also print url in raiko container by modify this get_blob_data: https://github.com/taikoxyz/raiko/blob/dc74ff1492bd7abf3984cb810a20613ef8c73c48/host/src/preflight.rs#L293

**Comment by quangtuyen88** [comment]
Oke .. Will test and update here @smtmfft

**Comment by quangtuyen88** [comment]
Hello I'm getting different errors today now . 

![Screenshot 2024-05-06 at 22 46 22](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/bc5cb1af-e91f-4d7f-907c-cee6fd3b73b7)

**Comment by quangtuyen88** [comment]
```
Processing withdrawals... Done in 0.000 seconds
Generating block header... Done in 0.000 seconds
2024-05-06T14:45:51.283437Z  INFO raiko_host::execution: Verifying final state using provider data ...
2024-05-06T14:45:51.283452Z  INFO raiko_host::execution: Final block hash derived successfully. 0x864946dd13052ace53d32b196540441642bc3563b388b369dccb56df55b69610
2024-05-06T14:45:51.283454Z  INFO raiko_host::execution: Final block header derived successfully. Header { parent_hash: 0x51b2a16eb4269c3013e27c5f3d2d68f22fbcda38f437d00fe51e7931b7b2315a, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0xffdc94aab53881413e11cf7ff2c132f07266a905, state_root: 0x6ef6ff9503a054d2b042031876c45023b3606e283c7553c401427829ee36682c, transactions_root: 0x48452d319cbd5067d64b53d1356e398c258914fb14809f6eb05a72171431da3d, receipts_root: 0x8f2e8a04b046b311fd31055f8439eb498d67c6453515611346617bfd656200a0, withdrawals_root: Some(0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421), logs_bloom: 0x00000000000080000000000000000000000000000000000000000000000000400000000000000000000000000010000000000000000000000000000000002140000000000000002000000000000000000000000200000000000000020000011000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000002000000041000000000000000000000000000000001004200000000000000000020000000000000200000000000020000000000000000008000000000020000000000000000000000000000000000000000000000000000000000000400000, difficulty: 0x0_U256, number: 96597, gas_limit: 240250000, gas_used: 176717, timestamp: 1715006616, mix_hash: 0x82b4f42b6754c26c8706940b71e2cf3f78b08f025ad0f288e0d10bf74374f7ea, nonce: 0, base_fee_per_gas: Some(99627953), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: 0x302e31382e302d64657600000000000000000000000000000000000000000000 }
Guest program peak memory used: 4.098204 MB
Generating proof...
WARNING: running SGX in hardware mode!
Current directory: "/opt/raiko/bin"

thread 'tokio-runtime-worker' panicked at /opt/raiko/provers/sgx/prover/src/lib.rs:246:48:
Unable to serialize input: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: task 36 panicked
```

**Comment by Brechtpd** [comment]
I saw the same error message a couple of days ago when I was trying to generate an SGX proof without running setup/bootstrap first. I don't know however why the error message is so bad though if this would be the case, you would expect a better error message for something like this so something we need to look into if that's the case.

**Comment by quangtuyen88** [comment]
> I saw the same error message a couple of days ago when I was trying to generate an SGX proof without running setup/bootstrap first. I don't know however why the error message is so bad though if this would be the case, you would expect a better error message for something like this so something we need to look into if that's the case.

Oke I will try boostrap again and let you know if I will get different err.

**Comment by bwoogmy** [comment]
Adding `http` actually fixed the error for me too!

**Comment by quangtuyen88** [comment]
Hello I will close this issue now. Since no more issue after added `http://` thanks
