### ISSUE TITLE
Problem  prover tx

### ISSUE THREAD

**Issue by lucajj3** [taikoxyz/simple-taiko-node#229]
### Describe the bug

After sync node.
I tried sending me 500 tokens at a time. 
1 time he proposed and proved both tx. 
While 2 or 3 times it only provided 1 tx and started giving this error: ERROR[05-03|20:28:21.708] Failed to request proof height=82196 error="Post \"localhost:8080\": unsupported protocol scheme \"localhost\"" endpoint=localhost:8080
I have raiko on the same machine. https://holesky.etherscan.io/address/0x8fC62f005CCbb73Eec39a7F23891cEAd2988A284

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
@lucajj3 are you using the most updated version of simple-taiko-node? You might have misconfigured the SGX_RAIKO_HOST in your .env

**Comment by lucajj3** [comment]
is the last version. 
SGX_RAIKO_HOST=localhost:8080

I also had these errors:
taiko_client_prover_relayer-1  | WARN [05-03|10:32:02.679] nonce too low                            service=prover tx=795f6f..1b09e5 nonce=11 gasTipCap=1,000,000,000 gasFeeCap=5,625,646,650 gasLimit=3,000,000 err="nonce too low: next nonce 12, tx nonce 11"
 WARN [05-03|10:32:50.844] nonce too low                            service=prover tx=512046..0f72f5 nonce=11 gasTipCap=1,100,000,000 gasFeeCap=6,188,211,315 gasLimit=258,096 err="nonce too low: next nonce 13, tx nonce 11"


today however with the arrival of the 1000 tokens, everything went perfectly

**Comment by quangtuyen88** [comment]
Hello @lucajj3 you can't use localhost or 0.0.0.0. The prover container will know localhost or 0.0.0.0 is itself IP address not raiko

Try with your `http://internal IP:8080` or `http://public_ip:8080`

Make sure you can connect that IP from prover container .
You can also try using `http://host.docker.internal:8080`

**Comment by lucajj3** [comment]
> Hello @lucajj3 you can't use localhost or 0.0.0.0. The prover container will know localhost or 0.0.0.0 is itself IP address not raiko
> 
> Try with your `http://internal IP:8080` or `http://public_ip:8080`
> 
> Make sure you can connect that IP from prover container . You can also try using `http://host.docker.internal:8080`

now i have edited my .env with SGX_RAIKO_HOST=http://XXX.XX.0.1:8080

now i have this error:   
ERROR[05-07|17:46:57.024] Failed to request proof   height=101,437 error="task 1295 panicked" endpoint=http://XXX.XX.0.1:8080

**Comment by RogerLamTd** [comment]
> > Hello @lucajj3 you can't use localhost or 0.0.0.0. The prover container will know localhost or 0.0.0.0 is itself IP address not raiko
> > Try with your `http://internal IP:8080` or `http://public_ip:8080`
> > Make sure you can connect that IP from prover container . You can also try using `http://host.docker.internal:8080`
> 
> now i have edited my .env with SGX_RAIKO_HOST=http://XXX.XX.0.1:8080
> 
> now i have this error: ERROR[05-07|17:46:57.024] Failed to request proof height=101,437 error="task 1295 panicked" endpoint=http://XXX.XX.0.1:8080
> 
> ERROR[05-07|17:50:38.025] Failed to request proof height=101,437 error="task 1339 panicked" endpoint=http://XXX.XX.0.1:8080

this looks like a raiko error, @smtmfft might be able to help; are there any other logs?

**Comment by lucajj3** [comment]
> > > Hello @lucajj3 you can't use localhost or 0.0.0.0. The prover container will know localhost or 0.0.0.0 is itself IP address not raiko
> > > Try with your `http://internal IP:8080` or `http://public_ip:8080`
> > > Make sure you can connect that IP from prover container . You can also try using `http://host.docker.internal:8080`
> > 
> > 
> > now i have edited my .env with SGX_RAIKO_HOST=http://XXX.XX.0.1:8080
> > now i have this error: ERROR[05-07|17:46:57.024] Failed to request proof height=101,437 error="task 1295 panicked" endpoint=http://XXX.XX.0.1:8080
> > ERROR[05-07|17:50:38.025] Failed to request proof height=101,437 error="task 1339 panicked" endpoint=http://XXX.XX.0.1:8080
> 
> this looks like a raiko error, @smtmfft might be able to help; are there any other logs?

@RogerLamTd just these, tell me if you have other commands or files to look for them

**Comment by RogerLamTd** [comment]
> > > > Hello @lucajj3 you can't use localhost or 0.0.0.0. The prover container will know localhost or 0.0.0.0 is itself IP address not raiko
> > > > Try with your `http://internal IP:8080` or `http://public_ip:8080`
> > > > Make sure you can connect that IP from prover container . You can also try using `http://host.docker.internal:8080`
> > > 
> > > 
> > > now i have edited my .env with SGX_RAIKO_HOST=http://XXX.XX.0.1:8080
> > > now i have this error: ERROR[05-07|17:46:57.024] Failed to request proof height=101,437 error="task 1295 panicked" endpoint=http://XXX.XX.0.1:8080
> > > ERROR[05-07|17:50:38.025] Failed to request proof height=101,437 error="task 1339 panicked" endpoint=http://XXX.XX.0.1:8080
> > 
> > 
> > this looks like a raiko error, @smtmfft might be able to help; are there any other logs?
> 
> @RogerLamTd just these, tell me if you have other commands or files to look for them

could you check the logs of your raiko container? `docker compose logs -f raiko` or something like that

**Comment by smtmfft** [comment]
Is your docker built from latest alpha7? if not, you could update and try again.
The prover panic has lots of reasons, and we are refining it. however, some high likely ones are: 1. bootstrap failure due to unsuccessful file loading, 2. unstable network makes the data fetching problematic. 3. a critical bug.
Also you can run prove_block.sh with like `prove_block taiko_a7 sgx 66666` to see if prover itself works. but remember to re-register the bootstrap as the script will refresh it. or you can edit the script to disable the refresh by set
```
"setup": false,
"bootstrap": false,
```

Enjoy the play :)

**Comment by lucajj3** [comment]
> Is your docker built from latest alpha7? if not, you could update and try again. The prover panic has lots of reasons, and we are refining it. however, some high likely ones are: 1. bootstrap failure due to unsuccessful file loading, 2. unstable network makes the data fetching problematic. 3. a critical bug. Also you can run prove_block.sh with like `prove_block taiko_a7 sgx 66666` to see if prover itself works. but remember to re-register the bootstrap as the script will refresh it. or you can edit the script to disable the refresh by set
> 
> ```
> "setup": false,
> "bootstrap": false,
> ```
> 
> Enjoy the play :)

I reinstalled the entire vps from 0. everything updated. Holensky knot mine. all on the same machine. first proposal and proved is ok without  errors. the second proved tx still gives me this error

ERROR[05-11|17:25:05.430] Failed to request proof                  height=125,808 error="task 64 panicked" endpoint=http://myexternalip:8080

**Comment by smtmfft** [comment]
> height=125,808 error="task 64 panicked

Any other info besides panic? we just updated the error report, now it should show the error log together with the panic,

**Comment by lucajj3** [comment]
> > height=125,808 error="task 64 panicked
> 
> Any other info besides panic? we just updated the error report, now it should show the error log together with the panic,

these are the errors it gives me now. I had everything installed 7 days ago.

[raikolog.txt](https://github.com/taikoxyz/simple-taiko-node/files/15373699/raikolog.txt)

**Comment by smtmfft** [comment]
Closed as stale
