### ISSUE TITLE
blob_sidecars RPC Call Error

### ISSUE THREAD

**Issue by goonerholic-crypto** [taikoxyz/simple-taiko-node#230]
### Describe the bug

taiko_client_driver-1    | ERROR[05-04|00:56:15.743] Block batch iterator callback error      error="failed to decode tx list: code=404, url=http://xx.xx.xx.xx:5052/eth/v1/beacon/blob_sidecars/1573481, body=response body:\n{\"code\":404,\"message\":\"Not found\"}: recv 404 NotFound response from API: did not receive 2xx response from API"

However, when I make a curl request or type the URL in the browser, I get all the required data. 
### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by goonerholic-crypto** [comment]
<img width="728" alt="Screenshot 2024-05-04 at 11 19 31 AM" src="https://github.com/taikoxyz/simple-taiko-node/assets/156572444/05ee53c2-ae37-48dd-957c-0e4351af4d6b">

**Comment by lucajj3** [comment]
i have same problem with beacon premium ankr service. Ankr support says: 
We did not detect any issues on the nodes or load balancer side. However, upon checking the one ticket we have reporting the issue with, we noticed that the reporter was using < url=https://rpc.ankr.com/premium-http/eth_holesky_beacon/eth/v1/beacon/genesis > - The private token in the path is missing.

Please note that "{"error":{"code":0,"message":"not authorized"}}" pops up when the private token is missing or if it is wrong.

**Comment by davidtaikocha** [comment]
> <img alt="Screenshot 2024-05-04 at 11 19 31 AM" width="728" src="https://private-user-images.githubusercontent.com/156572444/327925669-05ee53c2-ae37-48dd-957c-0e4351af4d6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NTc2NjcsIm5iZiI6MTcxNDk1NzM2NywicGF0aCI6Ii8xNTY1NzI0NDQvMzI3OTI1NjY5LTA1ZWU1M2MyLWFlMzctNDhkZC05NTdjLTBlNDM1MWFmNGQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwMTAyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTliNmVlNTgzMTdmZmQ1OTVjMTEyNjQzOTM3ZmU0NzA4MmY5YWJkMDc4YmY5YzU1Nzk3MDlhZTMyNGFkYzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IhqmS4nOBu4BsQ0AZZWCc7sOuAmzht_DZ8D6lhEpaLM">

Looks like there is some latency in your L1 beacon node, the node should have retired again after getting 404 error and the L2 block should have mined, plz check :)
