### ISSUE TITLE
error=SGX_INVALID_INSTANCE 

### ISSUE THREAD

**Issue by StoneMac65** [taikoxyz/simple-taiko-node#233]
### Describe the bug

during testing new batches for proof I see these error. each time that block would be failed on Holesky explorer. I want to see what might be the cause and how to make sure it wont happen more often. in around 200 proofs there were 10 blocks with same situation. want to make necessary changes to bring up efficiency of my prover 

### 
**taiko_client_prover_relayer-1 logs**

```
taiko_client_prover_relayer-1  | ERROR[05-04|06:36:29.492] Failed to submit proof                   blockID=84071 tier=200 txHash=aa6e9e..f7c3b9 error=SGX_INVALID_INSTANCE
taiko_client_prover_relayer-1  | ERROR[05-04|06:36:45.597] Failed to submit proof                   blockID=84117 tier=200 txHash=a3455d..2de238 error=SGX_INVALID_INSTANCE
taiko_client_prover_relayer-1  | ERROR[05-04|07:52:09.980] Failed to submit proof                   blockID=84391 tier=200 txHash=7d6505..7c4e49 error=SGX_INVALID_INSTANCE
```

Holesky explorer

![image](https://github.com/taikoxyz/simple-taiko-node/assets/103312943/7bcc2bf6-380f-4291-a63e-c056c55ca15a)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
@smtmfft looks like some issue with RA?

**Comment by smtmfft** [comment]
> @smtmfft looks like some issues with RA?

I guess more likely raiko, as RA does nothing in prove submission.

@StoneMac65 Can you provide tx hash?? I can see if sth wrong in proof itself.

**Comment by StoneMac65** [comment]
> > @smtmfft looks like some issues with RA?
> 
> I guess more likely raiko, as RA does nothing in prove submission.
> 
> @StoneMac65 Can you provide tx hash?? I can see if sth wrong in proof itself.

sure, this is one of the failed txs. it mostly happens when I try 4 or 8 batches together

`https://holesky.etherscan.io/tx/0xc861c21050fb41d76049f9765184012917660b0e3422d55936971f9e223fbedb`

by batches I mean, I keep ttkoh on seperate wallet and send them manually to check prover condition first and avoid fast slashing

**Comment by StoneMac65** [comment]
I also saw this on Raiko logs. single error which was completely new

```
raiko  | Execution iteration 17...
raiko  | spec_id: SHANGHAI
Tx transact time: 0.018 seconds
raiko  | Tx misc time: 0.000 seconds
Processing withdrawals... Done in 0.000 seconds
Generating block header... Done in 0.000 seconds
raiko  | thread 'tokio-runtime-worker' panicked at host/src/execution.rs:97:10:
raiko  | Failed to fetch required data for block: **error decoding response body**
raiko  | 
raiko  | Caused by:
raiko  |     0: error decoding response body
raiko  |     1: error reading a body from connection
raiko  |     2: end of file before message length reached
raiko  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fetching storage proof 348/885...Error: task 619 panicked
raiko  | # Generating proof for block 86181 on taiko_a7
raiko  | Generating input...
raiko  | Fetching block data...
raiko  | block.hash: 0x7e8e87c5721874b458aafd69e7b51315c14493c3fe3c61965bee1f6fbd660b57
raiko  | block.parent_hash: 0xc35530b0f16674a6be4db67033373e9edb296426248d47cecaa522f93058c155
raiko  | block gas used: 19014652
raiko  | block transactions: 47
raiko  | anchor L1 block id: 1477455
raiko  | anchor L1 state root: 0x31f5cb3c85982b4a90a399351cd5bd124c17e9159c5ee2e5029dabfc63ad7e7a
raiko  | l1_state_root_block hash: 0xe863d325b13dd1401c2f9c39845b0325ee2fca3a1ba70bca202f2291de85f024
raiko  | blob active
Fetching block data... Done in 3.474 seconds
```
