### ISSUE TITLE
Proposer behavior

### ISSUE THREAD

**Issue by brachsterX** [taikoxyz/simple-taiko-node#236]
### Describe the bug

Not sure if intended. Proposer does not drop the transaction even if it is beyond the set gas limit. 

![image](https://github.com/taikoxyz/simple-taiko-node/assets/97795503/8f857679-9daf-493c-8bc9-31b1d3f25a0e)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Looks like your L1 node is not mining new blocks?

**Comment by quangtuyen88** [comment]
> Looks like your L1 node is not mining new blocks?

I think this is an issue when you already received response from Prover and try publish propose transaction .

**Comment by davidtaikocha** [comment]
> > Looks like your L1 node is not mining new blocks?
> 
> I think this is an issue when you already received response from Prover and try publish propose transaction .

Yeah after pushing the transaction, client failed to see that transaction mined on L1

**Comment by brachsterX** [comment]
> Looks like your L1 node is not mining new blocks?

Using blockpi endpoint for L1 node. I think it's not about rate limiting as it's set at 1000 reqs/min.

**Comment by brachsterX** [comment]
Additionally, I've noticed that proposers don't get rewards which is supposedly to be on L2?

![image](https://github.com/taikoxyz/simple-taiko-node/assets/97795503/a1e1b862-1a39-4eaf-a275-ed579aa77867)

Successfully proposed 2 blocks. See: https://holesky.etherscan.io/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2
L2 assets: https://hekla.taikoscan.network/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2

**Comment by StoneMac65** [comment]
Actually I noticed something. I set zkpool endpoint just as a sample for my proposer and also to let other users propose to my prover. I noticed the proposer randomly tries to connect to default relayer port or my own prover. that value already been taken out but still there are some cases of retry. and it prints I/O timeout message. I just disabled proposer completely to see the effects

**Comment by davidtaikocha** [comment]
> Additionally, I've noticed that proposers don't get rewards which is supposedly to be on L2?
> 
> ![image](https://private-user-images.githubusercontent.com/97795503/328086268-a1e1b862-1a39-4eaf-a275-ed579aa77867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODEwNDQsIm5iZiI6MTcxNTE4MDc0NCwicGF0aCI6Ii85Nzc5NTUwMy8zMjgwODYyNjgtYTFlMWI4NjItMWEzOS00ZWFmLWEyNzUtZWQ1NzlhYTc3ODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1MDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMzBhNDE1MmUyNTI5MDliODBlOTY0Nzg0YjZhMWJjMWFiZWMzMWRjOTc5MjIzYTc0ZTJmMzY0YWVlMTA2N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJT1qw_V_AuQjk6tv4OF-5xATf7NvaiYGurdnt3ACIs)
> 
> Successfully proposed 2 blocks. See: https://holesky.etherscan.io/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2 L2 assets: https://hekla.taikoscan.network/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2

I can see the L2 block gas fee income here: https://hekla.taikoscan.io/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2/coin-balances#address-tabs

**Comment by brachsterX** [comment]
> > Additionally, I've noticed that proposers don't get rewards which is supposedly to be on L2?
> > ![image](https://private-user-images.githubusercontent.com/97795503/328086268-a1e1b862-1a39-4eaf-a275-ed579aa77867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODEwNDQsIm5iZiI6MTcxNTE4MDc0NCwicGF0aCI6Ii85Nzc5NTUwMy8zMjgwODYyNjgtYTFlMWI4NjItMWEzOS00ZWFmLWEyNzUtZWQ1NzlhYTc3ODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1MDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMzBhNDE1MmUyNTI5MDliODBlOTY0Nzg0YjZhMWJjMWFiZWMzMWRjOTc5MjIzYTc0ZTJmMzY0YWVlMTA2N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJT1qw_V_AuQjk6tv4OF-5xATf7NvaiYGurdnt3ACIs)
> > Successfully proposed 2 blocks. See: https://holesky.etherscan.io/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2 L2 assets: https://hekla.taikoscan.network/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2
> 
> I can see the L2 block gas fee income here: https://hekla.taikoscan.io/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2/coin-balances#address-tabs

There must be some changes made recently as the history shows there were no rewards for the 10 blocks proposed before the rewards came in. 
The rewards came in on block 99263. https://hekla.taikoscan.io/address/0x450Cfc1c5E4d4401e7C20d2Ab98c99030fF030d2/validations#address-tabs

**Comment by davidtaikocha** [comment]
<img width="1244" alt="image" src="https://github.com/taikoxyz/simple-taiko-node/assets/104078303/d5d12d88-3f1d-4c17-9389-8dfab465a2c0">
<img width="1267" alt="image" src="https://github.com/taikoxyz/simple-taiko-node/assets/104078303/08607959-af9f-44cf-ab11-f1cf626ff4eb">

the latest reward is on 104909 which makes sense since 105317 is an empty block (only contains the system anchor transaction)

**Comment by brachsterX** [comment]
Aha! Thanks for the clarification @davidtaikocha !

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/simple-taiko-node/issues/236#issuecomment-2100892552
