### ISSUE TITLE
Failed to submit proof when submit large batch prove transactions

### ISSUE THREAD

**Issue by quangtuyen88** [taikoxyz/simple-taiko-node#241]
### Describe the bug

I'm getting error when try prove 36 block proofs. Got failed 4 blocks with same error as below : 

![Screenshot 2024-05-08 at 21 46 01](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/d9428728-3b29-48aa-b4af-4ff89c7bdfbe)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by quangtuyen88** [comment]
![Screenshot 2024-05-10 at 09 31 05](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/6c7f118e-07d2-4932-a0b1-c75456ca7a2b)
Got another batch with the same error 9 hours ago.

**Comment by mask-pp** [comment]
This error may be caused by the chain reorg, but don’t worry that the failed proof will be resubmitted.

**Comment by quangtuyen88** [comment]
> This error may be caused by the chain reorg, but don’t worry that the failed proof will be resubmitted.

I'm good with this issue failed proof will be resubmitted.. do we need add more log to clear on err log like` execution reverted will retry ..` ?

**Comment by mask-pp** [comment]
Great suggestion, we will take it into consideration, but it is not the most urgent matter right now.
