### ISSUE TITLE
Proof submission reverted after remove TX_GAS_LIMIT

### ISSUE THREAD

**Issue by quangtuyen88** [taikoxyz/simple-taiko-node#242]
### Describe the bug

I pulled the latest code and try to start my prover and got this err : 

```
taiko_client_prover_relayer-1  | ERROR[05-08|14:44:59.147] Proof submission reverted                blockID=105,295 minTier=100 error="failed to create the tx: operation failed permanently after 30 attempts: failed to estimate gas: execution reverted"
```
![Screenshot 2024-05-08 at 22 51 54](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/b84bb84c-ab0c-4735-90e9-f7d5407d89a7)

not sure if it's related this PR : 
https://github.com/taikoxyz/simple-taiko-node/pull/239/files

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
I think if it will reverted in gas estimation, it will revert on chain too, could u give me your prover address?

**Comment by quangtuyen88** [comment]
> I think if it will revert in gas estimation, it will revert on chain too, could u give me your prover address?

Hello this my prover address : `0x499593d3C7D04A911059750aBAC350d8fd2A111c`

**Comment by quangtuyen88** [comment]
I reverted the change for this value `TX_GAS_LIMIT=3000000` in my prover again and tested with 1 block it's fine. 
I will use the new setting for testing again

**Comment by quangtuyen88** [comment]
All is good today. I will close ticket. Thanks
