### ISSUE TITLE
"Protocol status"   stuck at    lastVerifiedBlockId=103,633

### ISSUE THREAD

**Issue by StoneMac65** [taikoxyz/simple-taiko-node#244]
### Describe the bug

I've been waiting for my bonds to be back to my wallet, it's been 28 hours now and I checked the logs and noticed that last verified block is locked at block     **lastVerifiedBlockId=103,633**.  gap between latest block head and last proved block reached to around 6000 blocks now

![image](https://github.com/taikoxyz/simple-taiko-node/assets/103312943/1eff6c9a-9c6a-430e-b199-82869a471bce)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
Some changes are happening, it might take a while for verified blocks to catch back up; thanks for the report @StoneMac65
