### ISSUE TITLE
Grafana setting for latest header, receipt, block

### ISSUE THREAD

**Issue by Papilllion** [taikoxyz/simple-taiko-node#246]
### Describe the bug

Not sure where to put this: Great job in shipping prometheus and grafana with the node. Just one observation in the "latest header", "latest receipt", "latest block" stats you should set the type to 'instant' instead of 'range' to give the accurate last state values and not the averages from the time series selected.
![image](https://github.com/taikoxyz/simple-taiko-node/assets/49870334/2c761710-25f1-4ffd-b461-5b749eab9b06)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
@Papilllion not sure if there's a way to have it default to instant queries, but feel free to open a PR if you know how!
