### ISSUE TITLE
Proof submission reverted

### ISSUE THREAD

**Issue by boblekov** [taikoxyz/simple-taiko-node#248]
### Describe the bug

Good afternoon, our favorite taiko team. Tell me, is there any way to fix this error? And do the tokens that the contract took from me as collateral burn? If this error occurs. Thank you :)
![image](https://github.com/taikoxyz/simple-taiko-node/assets/96989524/4d4d3a36-4058-43d0-9aa7-f096b71360c6)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by quangtuyen88** [comment]
This is same err mentioned here @boblekov https://github.com/taikoxyz/simple-taiko-node/issues/241#issue-2285664631
