### ISSUE TITLE
No Prover transaction without error on prover client

### ISSUE THREAD

**Issue by quangtuyen88** [taikoxyz/simple-taiko-node#253]
### Describe the bug

My prover was working well and showing this err 

`taiko_client_driver-1          | ERROR[05-12|13:16:01.526] Process new L1 blocks error              error="trigger beacon sync error: unexpected ForkchoiceUpdate response status: VALID"`
I can see many propose transfer transactions but not prover transaction without other errors showing on the prover client

![Screenshot 2024-05-13 at 09 58 38](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/f77f8ab7-3547-4db6-a321-63f3e5d5fbab)
 
 https://holesky.etherscan.io/address/0x499593d3C7D04A911059750aBAC350d8fd2A111c#tokentxns

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by quangtuyen88** [comment]
I have reregister my SGX instance 31h ago.. and after 17 blocks above err showing and all tokens slashed after that

https://holesky.etherscan.io/tx/0xb6c75911009e1dbb831d8d952e7b97abf7bbafa25a212a013a28cc2c16152133
Taiko mono latest commit : 
```
commit dd8725f8d27f835102fa3c5a013003090268357d (HEAD -> main, tag: protocol-v1.5.0, origin/main, origin/HEAD)
Author: taiko-bot <160625009+taiko-kitty@users.noreply.github.com>
Date:   Sat May 11 02:24:47 2024 -0400

    chore(main): release protocol 1.5.0 (#17060)

    Co-authored-by: Daniel Wang <99078276+dantaik@users.noreply.github.com>
```
    
  Raiko repo latest commit : 
 ```
    commit 0c5442bae0cd9a2b55c68b1f5b1e5c7823b5b733 (HEAD -> taiko/alpha-7, origin/taiko/alpha-7)
Author: smtmfft <99081233+smtmfft@users.noreply.github.com>
Date:   Sat May 11 18:29:01 2024 +0800

    feat(raiko): make all enclave have the same signer (#183)

    * feat(raiko): put gramine-signer into docker structure to ensure all guest has the same signer

    Signed-off-by: smtmfft <smtm@taiko.xyz>

    * add .pem

    Signed-off-by: smtmfft <smtm@taiko.xyz>

    ---------

    Signed-off-by: smtmfft <smtm@taiko.xyz>
 ```
 
 simple taiko node : 
 ```
    commit 02c27e9d5ac85838ca0948c9cc28a458a16154ab (HEAD -> main, origin/main, origin/HEAD)
Author: David <david@taiko.xyz>
Date:   Sat May 11 10:19:53 2024 +0800

    chore(ci): introduce `Close Inactive Issues` workflow (#249)
```

**Comment by mask-pp** [comment]
> ### Describe the bug
> My prover was working well and showing this err
> 
> `taiko_client_driver-1 | ERROR[05-12|13:16:01.526] Process new L1 blocks error error="trigger beacon sync error: unexpected ForkchoiceUpdate response status: VALID"` I can see many propose transfer transactions but not prover transaction without other errors showing on the prover client
> 
> ![Screenshot 2024-05-13 at 09 58 38](https://private-user-images.githubusercontent.com/5916248/329900662-f77f8ab7-3547-4db6-a321-63f3e5d5fbab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDkyODUsIm5iZiI6MTcxNTc0ODk4NSwicGF0aCI6Ii81OTE2MjQ4LzMyOTkwMDY2Mi1mNzdmOGFiNy0zNTQ3LTRkYjYtYTMyMS02M2YzZTVkNWZiYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMDQ1NjI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ0NzM1ODBlYmExYTUwZmY0ZDdlY2E2MDNlZDMxZjQ0NzBkM2Y4NGVkZTA2ZjZkMWU3Y2M1YzE4YmQyNjc1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5Bx91qxZkVHIl2V5ypR1egAjPO3oMEXMJAKxrr-KC6Q)
> 
> https://holesky.etherscan.io/address/0x499593d3C7D04A911059750aBAC350d8fd2A111c#tokentxns
> 
> ### Steps to reproduce
> Steps to reproduce here.
> 
> ### Spam policy
> * [x]  I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

@quangtuyen88 Can you make sure your taiko-geth's `--taiko` flag is set?

**Comment by mask-pp** [comment]
@quangtuyen88 Can you make sure that the l2chain appeared reorg?

**Comment by quangtuyen88** [comment]
> @quangtuyen88 Can you make sure that the l2chain appeared reorg? If it is caused by reorg, it is normal and will be repaired during the next trigger process.

I have no longer got this issue with new update and resync l2 service... feel close this ticket. thanks
