### ISSUE TITLE
error=SGX_INVALID_INSTANCE

### ISSUE THREAD

**Issue by boblekov** [taikoxyz/simple-taiko-node#254]
### Describe the bug

Hello everyone, another new bug :) Everything is fine in the raiko logs.
Pls help :) It seems that because of this error, the tokens are not returned back after a day.
![image](https://github.com/taikoxyz/simple-taiko-node/assets/96989524/889dd87f-9021-4365-8cb1-a5df2d8aa85d)
![image](https://github.com/taikoxyz/simple-taiko-node/assets/96989524/15408563-80a2-42dd-af94-184ad8897b57)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by boblekov** [comment]
![image](https://github.com/taikoxyz/simple-taiko-node/assets/96989524/161573eb-891c-440f-bd99-929ef435c134)

**Comment by boblekov** [comment]
![image](https://github.com/taikoxyz/simple-taiko-node/assets/96989524/a1d9a707-8d9e-4343-b2c6-1cb0d3e5f77e)

**Comment by boblekov** [comment]
https://holesky.etherscan.io/address/0x267717e150804347581c77214b558fa5a6255ed5
I saw that StoneMac65 already has the same problem. I stopped the node for a day to see how many tokens would be returned. Today I started the node, and the first 4 blocks were successfully confirmed. But then there were only errors.
![image](https://github.com/taikoxyz/simple-taiko-node/assets/96989524/5e5ca910-a06b-4c4e-989e-e49896d39386)
I saved the raiko logs to a text file. I hope this will help you figure it out.
[root@taiko~raikodocker# sudo docker.txt](https://github.com/taikoxyz/simple-taiko-node/files/15293875/root%40taiko.raikodocker.sudo.docker.txt)

**Comment by smtmfft** [comment]
> {"instance_address":"0xBC778F1aD707eB0f5637b836289AC68D15f8c6a7","proof":"0x000000debc778f1ad707eb0f5637b836289ac68d15f8c6a790df551f8be175b89a3b551ba95fb9f5ef248baff9ebfce95b73ecd78ed2e8426351cb188cee464db7c11bb876c766156317314ee83775611b560d5684b0f0101c",...

From the log, your proof comes from pubkey 0xBC778F1aD707eB0f5637b836289AC68D15f8c6a7, with sgx_id: 222 (0x000000de). But in contract the instance pubkey is: 0xE92666aFfab8967C7fCf41d83e3D216B9C7aBF3a, please double check your registered sgx id.

**Comment by boblekov** [comment]
I have registered a new instance with id=5005. And such a mistake did not happen again. Before that, I reinstalled the system and tried to leave the old address with id=222. But the strangest thing is that some blocks were successfully checked, and then the error occurred at the old address. Thanks for your reply. It would be nice if you would make a manual so that when we completely reinstall the system, we can leave the old address. Because I don't think it's the best idea to register a new instance every time. Thank you guys, you are the best <3

**Comment by smtmfft** [comment]
Good to know it solves you issue :)
Yes, you can keep the bootstrap setting, provided that the raiko & sgx related config has no updates. So, if there is no change, you can save these 2 files, config.json & priv.key in ~/.config/raiko/config(/secrets, respectively), and just run raiko (without init). Once you run init, the priv key will be overrided, and instance changes, so you need to do re-register again.

**Comment by boblekov** [comment]
Great, I'll know, thanks!
