### ISSUE TITLE
Prover MIN_TKO_BALANCE not taken into account and unit seems not in Wei

### ISSUE THREAD

**Issue by 0xm51** [taikoxyz/simple-taiko-node#260]
### Describe the bug

After testing this prover setting (MIN_TKO_BALANCE) I probably faced 2 issues :

1. The unit seems in ether and not wei as commented, because if we set 250000000000000000000 it never proves with WARN message about prover balance not OK (even with >3k TTKOh)
2. And if I set in ether (250) all TTKOh are gone once I start proving again.

So potentialy 2 issues, one about the unit to choose and also maybe not taken into account at all

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by YoGhurt111** [comment]
About 1, the comment of `prover.minTaikoTokenBalance` is `Minimum Taiko token balance without decimal a prover wants to keep`. `without decimal` means the unit is in ether(1e18) not in wei.

**Comment by YoGhurt111** [comment]
If you want to set 250000000000000000000 as your prover's minimum amount without decimal of TTKOh and it does prove, you should keep `prover.minTaikoTokenBalance = 250` and your prover balance of TTKOh > 250

**Comment by YoGhurt111** [comment]
About 2, can you provide your prover address?

**Comment by 0xm51** [comment]
Thanks for 1, ok for ether unit :)
Here is my prover account `0x9af56F0753DB29D51460D0c85F36b0BD12B39e6f`

**Comment by YoGhurt111** [comment]
What's the balance of your TTKOh when you start proving again? 
Each block you prove requires 1640 TTKOh as `contestBond` first. And these `contestBond` will be back until your proof is verified.
So if you submit proof constantly,  in a short period of time, your balance will be “gone” temporarily.

**Comment by 0xm51** [comment]
> What's the balance of your TTKOh when you start proving again? Each block you prove requires 1640 TTKOh as `contestBond` first. And these `contestBond` will be back until your proof is verified. So if you submit proof constantly, in a short period of time, your balance will be “gone” temporarily.

If I well remember I had 3k tTKOh when start proving again with MIN_TKO_BALANCE=250 and it was just before this propose Tx `0x291491dc322438fdb7be90c06cdb73b3277b53a9dcd69de846f63fdefd65b4ae` (May-19-2024 04:26:00 PM +UTC)

Meanwhile I see that the usual Approve Tx which normaly occurs after each node restart  didn't occur here... Actualy it occured after the first propose Tx and long time after node start.  So maybe I faced an unexpected behaviour not related to MIN_TKO_BALANCE...
OK closure thank you.
