### ISSUE TITLE
Failed to submit proof   blockID=184,824 tier=200 txHash=45c11b..da39a4 error=<nil>

### ISSUE THREAD

**Issue by quangtuyen88** [taikoxyz/simple-taiko-node#264]
### Describe the bug

I can see my prover try to prove 19 blocks proof but failed 4 blocks with same errs 
```
taiko_client_prover_relayer-1  | ERROR[05-21|12:43:04.011] Failed to submit proof                   blockID=184,824 tier=200 txHash=45c11b..da39a4 error=<nil>
taiko_client_prover_relayer-1  | ERROR[05-21|12:43:05.162] Failed to submit proof                   blockID=184,827 tier=200 txHash=135cbf..94ddde error=<nil>
taiko_client_prover_relayer-1  | ERROR[05-21|12:43:05.289] Failed to submit proof                   blockID=184,826 tier=200 txHash=71eab4..78b8bd error=<nil>
taiko_client_prover_relayer-1  | ERROR[05-21|12:43:06.333] Failed to submit proof                   blockID=184,823 tier=200 txHash=94e5c7..e393d7 error=<nil>
```
![Screenshot 2024-05-21 at 21 40 06](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/dd6557be-3ed0-41a8-bbb4-7a29d78fcc50)
I can see successful 16 prove transactions succcessful only. mean 3 blocks got slashed with weird issue

![Screenshot 2024-05-21 at 21 42 36](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/d6ce8438-a9c1-4346-8129-7edb6bd3c442)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by StoneMac65** [comment]
is it different error from

[https://github.com/taikoxyz/simple-taiko-node/issues/241#issuecomment-2103696265](url) ?

**Comment by quangtuyen88** [comment]
> [https://github.com/taikoxyz/simple-taiko-node/issues/241](url)

Yes it's the same but actually it does not retry resubmit.. I can see proven transaction count is not matched with total transferred tokens

**Comment by quangtuyen88** [comment]
I also getting weird err today.
![Screenshot 2024-05-23 at 01 46 39](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/7e35ac23-e544-4258-97b7-0466004f23e6)
```
taiko_client_prover_relayer-1  | ERROR[05-22|17:08:39.108] Failed to request proof                  height=192,636 error="Can not serialize input for SGX io error: Broken pipe (os error 32), output is Ok(Output { status: ExitStatus(unix_wait_status(256)), stdout: \"Starting one shot mode\\nGlobal options: GlobalOpts { secrets_dir: \\\"/root/.config/raiko/secrets\\\", config_dir: \\\"/root/.config/raiko/config\\\" }, OneShot options: OneShotArgs { sgx_instance_id: 3603 }\\nmemory allocation of 32 bytes failed\\n\", stderr: \"Gramine is starting. Parsing TOML manifest file, this may take some time...\\n-----------------------------------------------------------------------------------------------------------------------\\nGramine detected the following insecure configurations:\\n\\n  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)\\n  - sys.insecure__allow_eventfd = true         (host-based eventfd is enabled)\\n  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)\\n\\nGramine will continue application execution, but this configuration must not be used in production!\\n-----------------------------------------------------------------------------------------------------------------------\\n\\n[P1:T4:sgx-guest] error: Out-of-memory in library OS\\n\" })" endpoint=http://xx.xx.xx.xx:8080
````

**Comment by quangtuyen88** [comment]
Hello do we have update on this err ?
I'm getting same err on mainnet today with failed tx :


![Screenshot 2024-06-08 at 21 18 33](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/8e473dd1-7f40-4197-9b0d-e3afa9470cc5)


failed prove tx : 

https://etherscan.io/tx/0xf06ea3cf22c35c7ea909ddcf8f73ff031cf5e02b3260eafa307af375809e10bf

**Comment by smtmfft** [comment]
> taiko_client_prover_relayer-1  | ERROR[05-22|17:08:39.108] Failed to request proof                  height=192,636 error="Can not serialize input for SGX io error: Broken pipe (os error 32), output is Ok(Output { status: ExitStatus(unix_wait_status(256)), stdout: \"Starting one shot mode\\nGlobal options: GlobalOpts { secrets_dir: \\\"/root/.config/raiko/secrets\\\", config_dir: \\\"/root/.config/raiko/config\\\" }, OneShot options: OneShotArgs { sgx_instance_id: 3603 }\\nmemory allocation of 32 bytes failed\\n\", stderr: \"Gramine is starting. Parsing TOML manifest file, this may take some time...\
> \n-----------------------------------------------------------------------------------------------------------------------\\nGramine detected the following insecure configurations:\\n\\n  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)\\n  - sys.insecure__allow_eventfd = true         (host-based eventfd is enabled)\\n  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)\\n\\nGramine will continue application execution, but this configuration must not be used in production!\\n
> -----------------------------------------------------------------------------------------------------------------------\\n\\n[P1:T4:sgx-guest] error: Out-of-memory in library OS\\n\" })" endpoint=http://xx.xx.xx.xx:8080
> ```


Never see before in our side, but some others mentioned that.
Error is still the libos out-of-memory, switch to bigger instance helps I guess..

BTW: you setup the mainnet? cool! 👍

**Comment by quangtuyen88** [comment]
@smtmfft Yes i think maybe that is an issue with memory with err code  `error: Out-of-memory in library OS` but actually it's different err with https://github.com/taikoxyz/simple-taiko-node/issues/264#issuecomment-2156037482.
Also my prover has 128G RAM and still free more than 64G ram. Not sure if that is issue with memory on Raiko host but actually that's log from prover side and no issue after generating proof on Raiko node..
That is old issue actually I have not got that err with new ver.

But this error still happening on mainnet : 
. The issue is to submit proof after generating https://github.com/taikoxyz/simple-taiko-node/issues/264#issuecomment-2156037482

**Comment by quangtuyen88** [comment]
> oh, so your proof is generated but failed to submit I saw you have 2 blocks, 44335 ok & 44330 fail. Can you see the tx in etherscan?? there was a issue in L1 gas evaluation, but with latest taiko-node should be fine.

Here is 2 failed tx : 
https://etherscan.io/tx/0xf06ea3cf22c35c7ea909ddcf8f73ff031cf5e02b3260eafa307af375809e10bf
https://etherscan.io/tx/0x10253246c70a1f3bf54bd265fb49bca70d78b41751a524fd438ba8cbe62d9fef

**Comment by smtmfft** [comment]
<img width="570" alt="image" src="https://github.com/taikoxyz/simple-taiko-node/assets/99081233/83a91547-a279-467b-82ee-b383530be13e">
yes, both are out of gas, you need to increase the gas limit.

**Comment by smtmfft** [comment]
Ref: https://discord.com/channels/984015101017346058/1152772683054981300/1250567442728484987

**Comment by smtmfft** [comment]
feel sad about that :(
Yes, I will talk with client guys for better error hint. 

what's the new error tag?? I think the proof should be accepted if it's still in the active window.

**Comment by quangtuyen88** [comment]
> <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/99081233/339196608-83a91547-a279-467b-82ee-b383530be13e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODAxMjYsIm5iZiI6MTcxODY3OTgyNiwicGF0aCI6Ii85OTA4MTIzMy8zMzkxOTY2MDgtODNhOTE1NDctYTI3OS00NjdiLTgyZWUtYjM4MzUzMGJlMTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAzMDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTljZTUwM2RmMTE4NzBhYjc4MjFkNmZlOGRhYzgwMjYzZDkyZTEwZGRmMzRmMzE1YTIyZDc1ZDhjZjQzMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PilVfuOJ6j2hkB4TaZ3x6uz1cY6y-fH3IKz9XB0iXSk">
> yes, both are out of gas, you need to increase the gas limit.

Do we have a plan to update or fix this error?
The issue is can't public prove txt because run out of gas.. The team has removed the default value in .env for the gas limit there it's perilous for mainnet.

**Comment by quangtuyen88** [comment]
> feel sad about that :( Yes, I will talk with client guys for better error hint.
> 
> what's the new error tag?? I think the proof should be accepted if it's still in the active window.

I changed to use my own beacon and the err is gone already.
