### ISSUE TITLE
Taiko driver shows and err on Hekla

### ISSUE THREAD

**Issue by amis13** [taikoxyz/simple-taiko-node#295]
### Describe the bug

I'm getting this on Hekla with the new repo:
after: `docker compose -f docker-compose-hekla.yml up -d`
```
taiko_client_driver-1  | failed to get protocol configs: abi: cannot marshal in to go type: length insufficient 224 require 256
```

### Steps to reproduce

Launching the node.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Should be fixed, plz try again, thanks for the feedback!

**Comment by amis13** [comment]
All fine now!
