### ISSUE TITLE
Failed to get blobs from beacon

### ISSUE THREAD

**Issue by quangtuyen88** [taikoxyz/simple-taiko-node#298]
### Describe the bug

I have pulled the latest code for simple taiko node and started my prover and god this error 

<img width="993" alt="Screenshot 2024-06-13 at 10 22 48" src="https://github.com/taikoxyz/simple-taiko-node/assets/5916248/71e2ffbc-734d-4019-8305-fe90a4e217d7">

I don't have this err with client tag v0.25.0. 
I'm using rpc.ankr.com service

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by quangtuyen88** [comment]
I'm trying to resync again seems that there is more issues with being out of sync from the client.

**Comment by quangtuyen88** [comment]
Same err
```
taiko_client_driver-1          | INFO [06-13|02:59:15.944] Failed to get blobs from beacon, try to use blob server. error="unexpected end of JSON input"
taiko_client_driver-1          | ERROR[06-13|02:59:15.944] Block batch iterator callback error      error="failed to fetch tx list: unexpected end of JSON input"
```

**Comment by YoGhurt111** [comment]
rpc.ankr.com service is not supported. You can retry SocialScan as your blob storage service.

**Comment by YoGhurt111** [comment]
https://thehemera.gitbook.io/blob-archive/api-reference You can refer to this document.

**Comment by quangtuyen88** [comment]
> rpc.ankr.com service is not supported. You can retry SocialScan as your blob storage service.

What do you mean it does not supported? I don'[t have any issue with ver v0.25.0 before and can prove 2 proofs already.. 
This is issue when I update taiko now to latest version v0.26.0 and the latest Raiko docker image.

Also if I copy link in the log to browser I can see response ok.

**Comment by YoGhurt111** [comment]
> > rpc.ankr.com service is not supported. You can retry SocialScan as your blob storage service.
> 
> What do you mean it does not supported? I don'[t have any issue with ver v0.25.0 before and can prove 2 proofs already.. This is issue when I update taiko now to latest version v0.26.0 and the latest Raiko docker image.
> 
> Also if I copy link in the log to browser I can see response ok.

Because you get a 404 from `rpc.ankr.com`. 
You can find out why it's wrong or use a blob storage service as a backup.
It's not about the version.

**Comment by quangtuyen88** [comment]
> > > rpc.ankr.com service is not supported. You can retry SocialScan as your blob storage service.
> > 
> > 
> > What do you mean it does not supported? I don'[t have any issue with ver v0.25.0 before and can prove 2 proofs already.. This is issue when I update taiko now to latest version v0.26.0 and the latest Raiko docker image.
> > Also if I copy link in the log to browser I can see response ok.
> 
> Because you get a 404 from `rpc.ankr.com`. You can find out why it's wrong or use a blob storage service as a backup. It's not about the version.

Did you read my comment above ? if I access URL directly I can get result and response 200.. DOn't understand why client try many times still got 404..

if there is delay my concern is did client do retry on that request ?
why request blob timeout and no reverted transaction for prover ?

it's mainnet and I got slashed 250 TAIKO because weird err and team said it not support rpc.ankr.com ???

**Comment by YoGhurt111** [comment]
<img width="794" alt="image" src="https://github.com/taikoxyz/simple-taiko-node/assets/23009382/3e3f1a60-7ce3-400f-bf7c-f4071854311b">
You copy the URL in the log here, you can get 200 response?

**Comment by quangtuyen88** [comment]
Yes

> <img alt="image" width="794" src="https://private-user-images.githubusercontent.com/23009382/340527001-3e3f1a60-7ce3-400f-bf7c-f4071854311b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODE1MzMsIm5iZiI6MTcxODY4MTIzMywicGF0aCI6Ii8yMzAwOTM4Mi8zNDA1MjcwMDEtM2UzZjFhNjAtN2NlMy00MDBmLWJmN2MtZjQwNzE4NTQzMTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAzMjcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NjUxYWZjNmU3OWUzMzBhNjEwNWFjYTMwMzk5NDE0NGUzM2ZlYWE5NjNhYWYzZjI1ZWRkM2NmMjc0YzI3YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PZhxNfkcx9CpxQRySlFCiiCHabPCcN4CuCB5eDuJSGM"> You copy the URL in the log here, you can get 200 response?

Yes. that is what i said

**Comment by YoGhurt111** [comment]
Copy it to me, let me try

**Comment by quangtuyen88** [comment]
> Copy it to me, let me try

How I can send you in dm ? it's including my api key.

**Comment by YoGhurt111** [comment]
Are you in the Taiko discord? You can send it to Gavin | Taiko.

**Comment by quangtuyen88** [comment]
> Gavin

Ok pls check your dm
