### ISSUE TITLE
Bug : [Mainnet] Prover aborted tx send due to critical error: failed to get tx into the mempool

### ISSUE THREAD

**Issue by quangtuyen88** [taikoxyz/simple-taiko-node#299]
### Describe the bug

I'm getting this err : 
```
taiko_client_prover_relayer-1  | ERROR[06-18|02:53:14.580] Submit proof error                       blockID=76054 minTier=200 error="aborted tx send due to critical error: failed to get tx into the mempool"
taiko_client_prover_relayer-1  | ERROR[06-18|02:56:38.646] Submit proof error                       blockID=76054 minTier=200 error="aborted tx send due to critical error: failed to get tx into the mempool"
taiko_client_prover_relayer-1  | ERROR[06-18|03:00:02.711] Submit proof error                       blockID=76054 minTier=200 error="aborted tx send due to critical error: failed to get tx into the mempool"
taiko_client_prover_relayer-1  | ERROR[06-18|03:03:26.777] Submit proof error                       blockID=76054 minTier=200 error="aborted tx send due to critical error: failed to get tx into the mempool"
taiko_client_prover_relayer-1  | ERROR[06-18|03:06:50.842] Submit proof error                       blockID=76054 minTier=200 error="aborted tx send due to critical error: failed to get tx into the mempool"
```
Log is fine yesterday.

![Screenshot 2024-06-18 at 11 03 19](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/ea63d918-721d-413d-9ba5-ab0c443d19e3)

Raiko log is good also

![Screenshot 2024-06-18 at 11 03 36](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/a81af6ca-d764-4aa0-9fe8-55909b72dceb)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by quangtuyen88** [comment]
![Screenshot 2024-06-18 at 11 13 41](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/aa4c8d6f-f4b1-48be-bd70-f820f7839be5)
I can see it's retrying each 3 or 4m . But still fail and it will run out of windows time for submit proof.. 

If you do retry failed need to reverted that prover transaction.
I can't accept lose 250 Taiko again because weird err on mainnet. that's not acceptable.

**Comment by quangtuyen88** [comment]
![Screenshot 2024-06-18 at 11 29 53](https://github.com/taikoxyz/simple-taiko-node/assets/5916248/b8d08f98-2928-4c33-8f15-b6111836663d)
The issue was solved after adding more ETH in prover balance.. 

1. We can't monitor our prover 24/24 because that weird err with gas bump.
2. Team need do action after some retry because 1h windows time for submitting proof.
3. We need better log clarify on issue so we can have better action. I can't even understand why I'm getting that err.

**Comment by YoGhurt111** [comment]
The recommended way is to add a prover balance alert.
And will optimize the logger.
