### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by boblekov** [taikoxyz/simple-taiko-node#300]
### Describe the bug

Hello taiko team. After the new update, the red color appeared in the logs :) In fact, everything works, but as far as I understand, since now we have the same address for the provider and the proposer, there are times when a node almost simultaneously wants to use the same wallet to send a transaction. And because of this, there is a conflict and an error. Is there any way to fix this? thank you <3
![image](https://github.com/taikoxyz/simple-taiko-node/assets/96989524/9811ecde-b4dd-4c75-aa8f-c812956886ad)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
Please consult the Deploy a ProverSet in the documentation, should be live soon! This problem occurs since you are using the same EOA for both proposer and prover, which allows you to prove; but you should deploy a ProverSet contract to prevent nonce issues and use separate EOAs for each service.
