### ISSUE TITLE
Add User Search Functionality

### ISSUE THREAD

**Issue by Rifkichrl** [taikoxyz/simple-taiko-node#314]
### Describe the feature request

Problem Description:
Currently, the application lacks a search function that allows users to search based on username.

New Feature Description:
Implement a search functionality on the home page that enables users to input a username and retrieve relevant user information based on the search criteria. The search should return a list of results matching the search query.

Steps to Implement:

Add Search Input: Introduce a text input field on the home page for users to enter a username.
Implement Search Function: Develop a backend function to handle user input, perform username-based searches, and return corresponding results.
Display Search Results: Display search results appropriately on the home page, formatted to match user expectations.
Acceptance Criteria:

 Users can input a username into the search input field.
 Search results display a list matching the entered username.
 Implementation integrates seamlessly into the existing application architecture.
Additional Information:
Include any technical specifications, UI design considerations, or other relevant details for implementing this feature effectively.

Ensure the description aligns with TaikoXYZ's development practices and standards for clarity and completeness. Adjust details as necessary based on project requirements and feedback from the team.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Rifkichrl** [comment]
Please provide me with a GitPOAP, please

**Comment by KorbinianK** [comment]
@Rifkichrl with that spam you'll just land on a blacklist and will certainly not get a POAP.
