### ISSUE TITLE
Beacon REST API does not support /path

### ISSUE THREAD

**Issue by goldsquid** [taikoxyz/simple-taiko-node#342]
### Describe the bug

Using Quicknode as Beacon REST API gives you a URL like

https://flashy-practical-river.quiknode.pro/58dd38bb48734ea713fdd6e0a898d8c8747d3261/

But using this will result in the client driver to try to connect to 

https://flashy-practical-river.quiknode.pro/eth/v1/config/spec

which fails as UNAUTHORIZED

### Steps to reproduce

use a free quicknode endpoint as rest api and start the client driver. check the logs.

**Comment by YoGhurt111** [comment]
Is https://flashy-practical-river.quiknode.pro/58dd38bb48734ea713fdd6e0a898d8c8747d3261/eth/v1/config/spec you expected?

**Comment by goldsquid** [comment]
It’s a non working example URL because I obfuscated the api key.

**Comment by YoGhurt111** [comment]
Yes, the format is like https://flashy-practical-river.quiknode.pro/xxx/eth/v1/config/spec

**Comment by goldsquid** [comment]
Yes and the log output from the docker container is missing the /<xxx>/
where it complains about connection issues

**Comment by davidtaikocha** [comment]
Should have been fixed, could u give v1.8.1 a try?

**Comment by YoGhurt111** [comment]
Let's wait for a while

**Comment by YoGhurt111** [comment]
@goldsquid You can have a try now, thanks for your feedback!

**Comment by goldsquid** [comment]
I managed to pull container
us-docker.pkg.dev/evmchain/images/taiko-client:sha-52a9362

and it contained the fix. thank you so much for your support.
