### ISSUE TITLE
The Taiko Node is not properly spinning up

### ISSUE THREAD

**Issue by Nomad-Free-Talent** [taikoxyz/simple-taiko-node#346]
### Describe the bug

I ran the holesky EL/CL nodes by using eth-docker and tried to follow this guide to spin up the taiko node.
https://docs.taiko.xyz/guides/node-operators/run-a-taiko-node-with-docker/
However, I'm getting these error from `simple-taiko-node-taiko_client_driver-1` container.
Could you help me to deal with this issue, please?
FYI, the holesky L1 node is fully synced right now.
![image](https://github.com/user-attachments/assets/2a493915-c739-469f-b6da-56705a6242e5)

### Steps to reproduce

Steps to reproduce here.

**Comment by RogerLamTd** [comment]
@Nomad-Free-Talent you might be using the wrong docker-compose file, please make sure you are using the hekla one.
