### ISSUE TITLE
Git clone issue

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/simple-taiko-node#4]
Running the command `git clone git@github.com:taikoxyz/simple-taiko-node.git` listed in the readme gives me the following error:

>Cloning into 'simple-taiko-node'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Using `git clone https://github.com/taikoxyz/simple-taiko-node.git` works fine

**Comment by cyberhorsey** [comment]
Do you have an SSH key set up and attached to your GitHub account?

**Comment by d1onys1us** [comment]
This is a valid friction point @wolfderechter , thanks. Actually it originally used https, but I thought ssh was more popular. I can add both options.

**Comment by wolfderechter** [comment]
#8
