### ISSUE TITLE
Instances/Parallelization

### ISSUE THREAD

**Issue by QustomQure** [taikoxyz/simple-taiko-node#44]
Hello, guys. I've seen that my taiko node didn't utilise full cpu to make zk proofs(32/32/300 not to mention all requirments is overkill tbh). It acts giving short cpu spikes. Is there any way i can use many instances of docker images and them not be collided with ports? And how exactly p2p connecting with network would work in that case? I mean if i open another ports for next docker instance, will it find peers and be able connect to network?

**Comment by davidtaikocha** [comment]
actually there is a `--lookup` flag in zkevm-chain, and a `--maxConcurrentProvingJobs` flag in taiko-client prover, so proving concurrently is feasible now, u can try this setup 🙂 (maybe need to read and learn some related code about lookup in zkevm-chain codebase)
