### ISSUE TITLE
CRIT [04-07] Failed to start Taiko client error="no contract code at given address"

### ISSUE THREAD

**Issue by alexkirillovtech** [taikoxyz/simple-taiko-node#47]
Hey team, I am running mode simple-taiko-node, but I can see huge amount of crit errors, which is constantly repeating.
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/51885928/230569668-18baa727-2173-4ecc-a48a-15dcdb8e8f7d.png">

I am sure that I provided valid data to .env file

The dashboard looks fine
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/51885928/230569758-48d387d2-cd42-41ab-99b1-557c7783a6e7.png">

Ping me you will need any more information

**Comment by rlg1860** [comment]
Same error for me

**Comment by rlg1860** [comment]
nevermind

**Comment by davidtaikocha** [comment]
I believe its because in `.env` file, wrong contract address was used.
