### ISSUE TITLE
Critical Error while starting node 

### ISSUE THREAD

**Issue by DockedFerret800** [taikoxyz/simple-taiko-node#49]
` CRIT [04-16|09:05:07.275] Failed to start Taiko client             error="invalid L1 prover private key: invalid length, need 256 bits"`

Morning. I keep getting error above in logs while starting Taiko node. Are there any problems with node right now?

**Comment by bruckbond** [comment]
probably you got your keys on infura.io, there you should choose sepolia instead of mainnet on eash tab (both http and websocket)

**Comment by bruckbond** [comment]
same problem

**Comment by davidtaikocha** [comment]
Please remove the `0x` prefix of the private keys, then i believe this issue will be addressed.
