### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/simple-taiko-node#62]
## Summary
I am getting:

`zkevm-chain-prover-rpcd The requested image's platform (linux/amd64) does not match the detected
host platform (linux/arm64/v8) and no specific platform was requested`

when running docker compose up.

**Comment by 2manslkh** [comment]
For additional context:

<img width="975" alt="image" src="https://github.com/taikoxyz/simple-taiko-node/assets/23635326/bc0d7b19-4a1f-44bb-9922-82143dc8849c">

**Comment by 2manslkh** [comment]
@davidtaikocha

**Comment by davidtaikocha** [comment]
actually this image is designed to be used in linux but not mac, since proof generation should be a resource intensive job which is not for PC. Just since this A3's circuits and  hardware requirements are too small so everyone can try that on PC, but anyway i can add the mac image if we want.

**Comment by d1onys1us** [comment]
> actually this image is designed to be used on linux but not mac, since proof generation should be a resource intensive job which is not for PC. Just since this A3's circuits and  hardware requirements are too small so everyone can try that on PC, but anyway i can add the mac image if we want.

okay let me close this issue then, i don't think it's worth it. if anyone disagrees, we can re-open the issue. if it's a very small task (like 5-10 min) and doesn't have any downsides feel free to add it, but no need to of course.

**Comment by d1onys1us** [comment]
> actually this image is designed to be used on linux but not mac, since proof generation should be a resource intensive job which is not for PC. Just since this A3's circuits and hardware requirements are too small so everyone can try that on PC, but anyway i can add the mac image if we want.

@davidtaikocha actually if it's an easy addition, can we add the `linux/arm64/v8` image for mac? i believe there is enough of a user base to qualify this, and running on a mac is not totally unreasonable

**Comment by RogerLamTd** [comment]
closed by https://github.com/taikoxyz/k8s-configs/pull/208

**Comment by rihardsgrislis** [comment]
The link posted by @RogerLamTd is broken now but I wanted to point out that I'm running into this issue on my macOS if it was supposed to be closed: " ! zkevm_chain_prover_rpcd The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested".
