### ISSUE TITLE
feature: build taiko node images for other platforms such as raspberry pi and aarch64

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/simple-taiko-node#81]
Nice to have feature to support running nodes on different platforms such as raspberry pi's and should be fairly easy with buildx

**Comment by M2l2koPOWER** [comment]
Node runs on ARM (aarch64) and no separate compilation is required. I checked on a virtual machine, but maybe there are some problems on real hardware?

**Comment by techriffic** [comment]
this one doesnt:
e6ddbad1cd89 gcr.io/evmchain/katla-proverd:latest "/bin/sh -c /script/…" 2 hours ago Restarting (1) 14 seconds ago simple-taiko-node-zkevm_chain_prover_rpcd-1

**Comment by ramshazz** [comment]
Interesting comment; however, Raspberry pi's are not the best hardware out there, I believe something like a light node could be developed to run on such hardware, team should definitely consider this.

**Comment by AhyanSch** [comment]
so can you run on a pi computer?

**Comment by flechemano** [comment]
> so can you run on a pi computer?

i will try if it is working too.
